import SignatureRenderer from "./SignatureRenderer";
import PaperContractDocument from "./PaperContractDocument";
import { signatureMethod } from "@/lib/contracts/security";

export default function ContractDocument({ contract, signed = false, unsignedMark = false, variant }) {
  const t = contract.templateSnapshot || {}, terms = t.terms || [], method = signatureMethod(contract), rep = t.sellerRepresentative || {};
  const layout = variant || contract.linkTemplate || "paper";
  if (layout === "paper") return <PaperContractDocument contract={contract} signed={signed} unsignedMark={unsignedMark}/>;
  const sig = signed ? <SignatureRenderer method={method} strokes={contract.signature} typedName={contract.signerName} className="buyer-signature-render"/> : null;
  return <div className={`contract-document contract-document--${layout}`} data-pages="8" data-template={layout}>
    <Page n={1} mark={unsignedMark}><Header t={t}/><Title>DELIVERY RECEIPT</Title><OrderTable contract={contract} delivery/><Checks values={contract.deliveryChecks}/><Title small>WARRANTIES</Title><WarrantySummary warranty={contract.warranty}/><p className="font-bold">{t.warrantyDisclaimer}</p></Page>
    <Page n={2} mark={unsignedMark}><Title>BUYER DECLARATIONS</Title><DeclarationList items={t.buyerDeclarations}/><SignaturePair contract={contract} rep={rep} buyerSignature={sig} signed={signed}/></Page>
    <Page n={3} mark={unsignedMark}><Header t={t}/><Title>ORDER</Title><OrderTable contract={contract}/><Prices contract={contract}/><Title>TERMS &amp; CONDITIONS</Title><p>This Agreement is entered into as of {date(contract.orderDate)} by and between Buyer and Seller, which jointly may be referred to as the “Parties.”</p><p className="whitespace-pre-line">{t.introduction}</p><Term term={terms[0]}/></Page>
    <Page n={4} mark={unsignedMark}>{terms.slice(1,7).map(x=><Term key={x.number} term={x}/>)}</Page>
    <Page n={5} mark={unsignedMark}>{terms.slice(7,11).map(x=><Term key={x.number} term={x}/>)}</Page>
    <Page n={6} mark={unsignedMark}>{terms.slice(11,13).map(x=><Term key={x.number} term={x}/>)}</Page>
    <Page n={7} mark={unsignedMark}><Term term={terms[13]}/><p className="mt-5 font-bold uppercase">{t.confirmationText}</p></Page>
    <Page n={8} mark={unsignedMark}><p className="font-bold">{t.witnessText}</p><SignaturePair contract={contract} rep={rep} buyerSignature={sig} signed={signed}/>{signed?<div className="signed-meta">Signed {dateTime(contract.signedAt)} UTC · {method === "typed_consent" ? "Typed consent" : "Drawn signature"}</div>:null}</Page>
  </div>;
}
function Page({n,mark,children}){return <section className="contract-letter-page">{mark?<div className="unsigned-mark">UNSIGNED COPY</div>:null}<div className="contract-page-content">{children}</div><footer>{n}</footer></section>}
function Header({t}){const c=t.company||{};return <header className="letter-header"><img src={t.logoUrl||"/logo.png"} alt="S & W Equipment"/><address><b>{c.name}</b><br/>{c.address}<br/>{c.cityStateZip}<br/>{c.phone}<br/>{c.email}<br/>{c.website}<small>{c.name} is a registered trade name of<br/>{c.legalName}</small></address></header>}
function Title({children,small=false}){return <h2 className={small?"letter-subtitle":"letter-title"}>{children}</h2>}
function OrderTable({contract:c,delivery=false}){return <div className="letter-table"><Row cells={[[delivery?"Invoice #":"Order #",c.orderNumber],[delivery?"Delivery Date":"Order Date",date(delivery?c.deliveryDate:c.orderDate)]]}/><Row cells={[["Buyer",buyer(c.buyer)],["Seller",seller(c.seller)]]}/><Row cells={[["Contact",[c.buyer?.contact||c.buyer?.name,c.buyer?.phonePrimary,c.buyer?.phoneSecondary].filter(Boolean).join("\n")],["Delivery Location",c.deliveryAddress]]}/><Row cells={[["Model",c.equipment?.model],["Year",c.equipment?.year],["Serial No.",c.equipment?.serialNumber]]}/><Row cells={[["Description & Notes",c.equipment?.description]]}/><Row cells={[["Make",c.equipment?.make],["Hours (if applicable)",c.equipment?.hours],["Price",money(c.pricing?.subtotal,c.pricing?.currency)]]}/></div>}
function Row({cells}){return <div className="letter-row">{cells.map(([k,v],i)=><div className="letter-cell" key={i}><b>{k}:</b><span>{v||" "}</span></div>)}</div>}
function Checks({values={}}){const labels={deliveryCompleted:"Delivery completed",buyerInspected:"Delivery inspection completed by Buyer",manualsGiven:"Applicable Owner's and Safety Manuals given",safetyExplained:"Use and safety procedures explained",maintenanceExplained:"Maintenance procedures explained"};return <div className="letter-checks">{Object.entries(labels).map(([k,v])=><p key={k}><i>{values[k]?"✓":""}</i>{v}</p>)}</div>}
function WarrantySummary({warranty:w={}}){const selected=warrantySelections(w);return <div className="letter-checks">{selected.manufacturer?<p><i>✓</i>Manufacturer&apos;s Warranty{w.expiresAt?` until ${warrantyDate(w.expiresAt)}`:""}</p>:null}{selected.trial?<p><i>✓</i>30-day trial</p>:null}{selected.other?<p><i>✓</i>Other: {w.text||"Not specified"}</p>:null}</div>}
function Prices({contract:c}){return <div className="letter-prices">{[["SUBTOTAL",c.pricing?.subtotal],["TAXES",c.pricing?.taxes],["SHIPPING AND HANDLING",c.pricing?.shipping],[`TOTAL PRICE (${c.pricing?.currency||"USD"})`,c.pricing?.total]].map(([k,v],i)=><p className={i===3?"font-bold":""} key={k}><span>{k}:</span><span>{money(v,c.pricing?.currency)}</span></p>)}</div>}
function DeclarationList({items=[]}){return <ul className="contract-declarations">{items.map((text,index)=><li key={index}><i aria-hidden="true"/><span>{text}</span></li>)}</ul>}
function Term({term,continuation=false}){if(!term)return null;const emphasis=[6,7].includes(Number(term.number));return <section className={`letter-term ${emphasis?"font-bold":""}`}><b>{continuation?"":`${term.number}. `}<u>{continuation?"":`${term.title}.`}</u></b>{!continuation?<span className="whitespace-pre-line"> {term.body}</span>:<span className="whitespace-pre-line">{term.body}</span>}</section>}
function SignaturePair({contract:c,rep,buyerSignature,signed}){const seller=rep.name||c.seller?.representativeName||"Seller Representative";return <div className="letter-signatures"><div><div className="letter-signature-space">{buyerSignature}</div><span className="line">Buyer Representative Signature</span><b className="line spaced">{signed?c.signerName:c.buyer?.name}</b><span>Buyer Representative Printed Name</span><span className="line spaced">{signed?date(c.signedAt):"Date"}</span></div><div><div className="letter-signature-space">{rep.signatureUrl?<img src={rep.signatureUrl} alt="Seller representative signature"/>:null}</div><span className="line">Signature - {seller}</span><b>{seller}</b><span>Seller Representative Printed Name</span><span className="line spaced">{rep.signedDate?date(rep.signedDate):"Date"}</span></div></div>}
function warrantySelections(w={}){const type=String(w.type||"").toLowerCase(),hasExplicit=[w.manufacturer,w.trial,w.other].some(value=>typeof value==="boolean");return hasExplicit?{manufacturer:w.manufacturer===true,trial:w.trial===true,other:w.other===true}:{manufacturer:type.includes("manufacturer"),trial:type.includes("30")||type.includes("trial"),other:Boolean(w.text)||(!type.includes("manufacturer")&&!type.includes("30")&&!type.includes("trial"))}}
function money(v,c="USD"){return new Intl.NumberFormat("en-US",{style:"currency",currency:c||"USD"}).format(Number(v||0))} function date(v){return v?new Intl.DateTimeFormat("en-US",{timeZone:"UTC",dateStyle:"medium"}).format(new Date(v)):""} function dateTime(v){return v?new Date(v).toISOString().replace("T"," ").slice(0,19):""} function buyer(b={}){return[b.name,b.company,b.address,b.cityStateZip].filter(Boolean).join("\n")} function seller(s={}){return[s.legalName||s.name,s.address,s.cityStateZip,s.phone,s.email].filter(Boolean).join("\n")}
function warrantyDate(v){return v?new Intl.DateTimeFormat("en-US",{timeZone:"UTC",month:"long",day:"numeric",year:"numeric"}).format(new Date(v)):""}
