import SignatureRenderer from "./SignatureRenderer";
import { signatureMethod } from "@/lib/contracts/security";
import { contractCompany } from "@/lib/contracts/company";
import { contractEquipmentItems, equipmentPrice } from "@/lib/contracts/equipment";
import { plainTextToRichHtml, sanitizeRichTextHtml } from "@/lib/contracts/richText";

const REFUND = "Right to Refund: The Client shall be entitled to a full refund of the initial purchase price provided that a written request for cancellation is submitted within 30 calendar days of the effective date. Refunds will be processed via the original payment method within [3] business days of approval.";

export default function PaperContractDocument({contract:c,signed=false,unsignedMark=false}){
  const t=c.templateSnapshot||{}, terms=t.terms||[], rep=t.sellerRepresentative||{};
  const hasMultipleEquipment=contractEquipmentItems(c).length>1;
  const t1=splitAt(terms[0]?.body,"in this Agreement."), t8=splitAt(terms[7]?.body,"expenses, demands,"), t10=paragraphs(terms[9]?.body), t11=splitAt(terms[10]?.body,"For further information,"), t14=paragraphs(terms[13]?.body);
  return <div className="contract-document contract-document--paper paper-original" data-pages={hasMultipleEquipment?9:8} data-template="paper">
    <PaperPage n={1} mark={unsignedMark} expand={hasMultipleEquipment}><PaperHeader t={t} c={c}/><h1>DELIVERY RECEIPT</h1><PartyGrid c={c} delivery/><EquipmentList c={c}/><Checks c={c}/>{!hasMultipleEquipment?<WarrantyBlock c={c} t={t}/>:null}</PaperPage>
    <PaperPage n={2} mark={unsignedMark} className={hasMultipleEquipment?"paper-page--warranties-declarations":""}>{hasMultipleEquipment?<WarrantyBlock c={c} t={t}/>:null}<h1 className="declarations-title">BUYER DECLARATIONS</h1><DeclarationList items={t.buyerDeclarations}/><PaperSignatures c={c} rep={rep} signed={signed}/></PaperPage>
    <PaperPage n={3} mark={unsignedMark} expand={hasMultipleEquipment}><PaperHeader t={t} c={c}/><h1>ORDER</h1><PartyGrid c={c}/><h3>DESCRIPTION:</h3><EquipmentList c={c}/><PriceBlock c={c}/>{!hasMultipleEquipment?<TermsOpening c={c} t={t} term={terms[0]} body={t1[0]}/>:null}</PaperPage>
    {hasMultipleEquipment?<>
      <PaperPage n={4} mark={unsignedMark} className="paper-page--terms-opening"><TermsOpening c={c} t={t} term={terms[0]} body={terms[0]?.body}/>{terms.slice(1,5).map(x=><PaperTerm key={x.number} term={x}/>)}</PaperPage>
      <PaperPage n={5} mark={unsignedMark}>{terms.slice(5,9).map(x=><PaperTerm key={x.number} term={x}/>) }<PaperTerm term={terms[9]} body={t10.slice(0,4).join("\n\n")}/></PaperPage>
      <PaperPage n={6} mark={unsignedMark}><PaperSubparagraphs items={t10.slice(4)}/><PaperTerm term={terms[10]}/></PaperPage>
      <PaperPage n={7} mark={unsignedMark}><PaperTerm term={terms[11]}/><NoticeAddresses c={c}/><PaperTerm term={terms[12]}/><PaperTerm term={terms[13]} body={t14.slice(0,4).join("\n\n")}/></PaperPage>
      <PaperPage n={8} mark={unsignedMark}><PaperSubparagraphs items={t14.slice(4)}/><p className="paper-confirmation">{t.confirmationText}</p></PaperPage>
      <PaperPage n={9} mark={unsignedMark}><WitnessText text={t.witnessText}/><PaperSignatures c={c} rep={rep} signed={signed}/></PaperPage>
    </>:<>
      <PaperPage n={4} mark={unsignedMark}><p>{t1[1]}</p>{terms.slice(1,7).map(x=><PaperTerm key={x.number} term={x}/>)}<PaperTerm term={terms[7]} body={t8[0]}/></PaperPage>
      <PaperPage n={5} mark={unsignedMark}><p>{t8[1]}</p>{terms.slice(8,10).map(x=><PaperTerm key={x.number} term={x}/>) }<PaperTerm term={terms[10]} body={t11[0]}/></PaperPage>
      <PaperPage n={6} mark={unsignedMark}><p className="paper-indent">{t11[1]}</p><PaperTerm term={terms[11]}/><NoticeAddresses c={c}/><PaperTerm term={terms[12]}/><PaperTerm term={terms[13]} body={t14.slice(0,2).join("\n\n")}/></PaperPage>
      <PaperPage n={7} mark={unsignedMark}><PaperSubparagraphs items={t14.slice(2)}/><p className="paper-confirmation">{t.confirmationText}</p></PaperPage>
      <PaperPage n={8} mark={unsignedMark}><WitnessText text={t.witnessText}/><PaperSignatures c={c} rep={rep} signed={signed}/></PaperPage>
    </>}
  </div>
}

function PaperPage({n,mark,expand=false,className="",children}){return <section className={`contract-letter-page${expand?" contract-letter-page--equipment-expanded":""}${className?` ${className}`:""}`}>{mark?<div className="unsigned-mark">UNSIGNED COPY</div>:null}<div className="contract-page-content">{children}</div><footer>{n}</footer></section>}
function WarrantyBlock({c,t}){return <><h2>WARRANTIES</h2><Warranties c={c}/><p className="paper-caps">{t.warrantyDisclaimer}</p><p className="paper-refund">{REFUND}</p></>}
function TermsOpening({c,t,term,body}){return <><h2 className="terms-title">TERMS &amp; CONDITIONS</h2><AgreementDate c={c}/><div className="paper-intro">{paragraphs(t.introduction).map((x,i)=><p key={i}>{x}</p>)}</div><PaperTerm term={term} body={body}/></>}
function PaperHeader({t,c}){const x=contractCompany(c);return <header className="paper-header"><img src={t.logoUrl||"/logo.png"} alt={x.name||"Seller company"}/><address><b>{x.name}</b><br/>{x.address}<br/>{x.cityStateZip}<br/>{x.phone}<br/>{x.email}<br/>{x.website}<small>{x.name} is a registered<br/>trade name of “{x.legalName}”</small></address></header>}
function PartyGrid({c,delivery=false}){const sellerValue=delivery?[c.seller?.legalName||c.seller?.name,c.seller?.phone,c.seller?.email].filter(Boolean).join("\n"):seller(c.seller);return <div className={`paper-party-grid ${delivery?"paper-party-grid--delivery":"paper-party-grid--order"}`}><Cell label={`${delivery?"Invoice":"Order"} #`} value={c.orderNumber}/><Cell label={`${delivery?"Delivery":"Order"} Date`} value={shortDate(delivery?c.deliveryDate:c.orderDate)}/><Cell label="Buyer" value={buyer(c.buyer)}/><Cell label="Seller" value={sellerValue}/><Cell label="Contact" value={[c.buyer?.contact||c.buyer?.name,c.buyer?.phonePrimary,c.buyer?.phoneSecondary].filter(Boolean).join("\n")}/><Cell label="Delivery Location" value={address(c)}/></div>}
function Cell({label,value}){return <div><b>{label}:</b><span>{value||" "}</span></div>}
function EquipmentList({c}){const items=contractEquipmentItems(c);return <div className={`paper-equipment-list equipment-count-${items.length}`}>{items.map((item,index)=><div key={index}>{items.length>1?<h4 className="paper-equipment-title">Equipment {index+1}</h4>:null}<div className="paper-equipment"><Cell label="Model" value={item.model}/><Cell label="Year" value={item.year}/><Cell label="Serial No" value={item.serialNumber}/><div className="paper-description"><b>Description &amp; Notes:</b><div className="contract-rich-text" dangerouslySetInnerHTML={{__html:sanitizeRichTextHtml(item.descriptionHtml||plainTextToRichHtml(item.description||""))}}/></div><Cell label="Make" value={item.make}/><Cell label="Hours (if applicable)" value={item.hours}/><Cell label="Price" value={priceLabel(item,c,items.length)}/></div></div>)}</div>}
function Checks({c}){const x=c.deliveryChecks||{};return <div className="paper-checks"><div><Check on={x.deliveryCompleted}>Delivery completed</Check><Check on={x.buyerInspected}>Delivery inspection completed by Buyer</Check><Check on={x.manualsGiven}>Applicable Owner’s and Safety Manuals given</Check></div><div><Check on={x.safetyExplained}>Use and safety procedures explained</Check><Check on={x.maintenanceExplained}>Maintenance procedures explained</Check></div></div>}
function Check({on,children}){return <p><i className={on?"checked":""} aria-hidden="true"/>{children}</p>}
function Warranties({c}){const w=c.warranty||{}, selected=warrantySelections(w);return <div className="paper-warranties"><Check on={selected.manufacturer}>The equipment is covered under a Manufacturer’s Warranty, which expires on <span className="fill-line">{warrantyDate(w.expiresAt)}</span></Check><Check on={selected.trial}>A 30-day trial begins upon delivery. If the Buyer does not reject the equipment by phone or in writing within 30 days, the sale becomes final and 'as-is' with no further seller liability.</Check><Check on={selected.other}>Other (explain): {w.text}</Check></div>}
function DeclarationList({items=[]}){return <ul className="paper-declarations">{items.map((text,index)=><li key={index}><i aria-hidden="true"/><span>{text}</span></li>)}</ul>}
function PriceBlock({c}){return <div className="paper-prices">{[["SUBTOTAL",c.pricing?.subtotal],["TAXES",c.pricing?.taxes],["SHIPPING AND HANDLING",c.pricing?.shipping],[`TOTAL PRICE (${c.pricing?.currency||"USD"})`,c.pricing?.total]].map(([k,v])=><p key={k}><b>{k}:</b><span>{money(v,c.pricing?.currency)}</span></p>)}</div>}
function priceLabel(item,c,count){const price=equipmentPrice(item,c,count);return price===null?"Included in subtotal":money(price,c.pricing?.currency)}
function AgreementDate({c}){const d=longDate(c.orderDate).split(" ");return <p className="agreement-date">This Agreement is entered into as of <span>{d.slice(0,2).join(" ")}</span> <span>{d[2]}</span> by and between Buyer and Seller, which jointly may be referred to as the “Parties.”</p>}
function PaperTerm({term,body}){if(!term)return null;const ps=paragraphs(body??term.body),emphasis=[6,7].includes(Number(term.number)),startsWithSub=/^[a-i]\.\s/.test(ps[0]||"");return <section className={`paper-term ${emphasis?"paper-term--emphasis":""}`}><div className="paper-term-head"><span>{term.number}.</span><u>{term.title}.</u>{!startsWithSub&&ps[0]?<p>{ps[0]}</p>:null}</div>{startsWithSub?<PaperSubparagraphs items={ps}/>:ps.length>1?<PaperSubparagraphs items={ps.slice(1)}/>:null}</section>}
function PaperSubparagraphs({items}){return <div className="paper-subparagraphs">{items.map((x,i)=>{const m=x.match(/^([a-i])\.\s*(.*)$/s),text=m?.[2]||x,[heading,rest]=subheading(text);return <div key={i}><span>{m?.[1]||String.fromCharCode(97+i)}.</span><p>{heading?<><u>{heading}</u>{" "}{rest}</>:text}</p></div>})}</div>}
function WitnessText({text=""}){const lead="IN WITNESS WHEREOF,";return <p className="paper-witness">{text.startsWith(lead)?<><strong>{lead}</strong>{text.slice(lead.length)}</>:text}</p>}
function NoticeAddresses({c}){const s=c.seller||{};return <div className="notice-addresses"><div>If to Buyer:<br/><br/>{buyer(c.buyer)}</div><div>If to Seller:<br/><br/>{s.legalName||s.name}<br/>{s.address}<br/>{s.cityStateZip}<br/>{s.phone}<br/>{s.email}</div></div>}
function PaperSignatures({c,rep,signed}){const method=signatureMethod(c), sellerName=rep.name||c.seller?.representativeName||"Seller Representative",sellerSignature=rep.signatureUrl||isDefaultSeller(sellerName)&&"/contract-seller-signature.png";return <div className="paper-signatures"><div><div className="paper-signature-space">{signed?<SignatureRenderer method={method} strokes={c.signature} typedName={c.signerName} className="buyer-signature-render"/>:null}</div><label>Buyer Representative Signature</label><div className="paper-printed">{signed?c.signerName:c.buyer?.name}</div><label>Buyer Representative Printed Name</label><div className="paper-date">{signed?shortDate(c.signedAt):""}</div><label>Date</label></div><div><div className="paper-signature-space">{sellerSignature?<img src={sellerSignature} alt="Seller representative signature"/>:null}</div><label>Signature - {sellerName}<br/>{c.seller?.name||c.templateSnapshot?.company?.name}</label><div className="paper-printed">{sellerName}</div><label>Seller Representative Printed Name</label><div className="paper-date">{rep.signedDate?sellerDate(rep.signedDate):""}</div><label>Date</label></div></div>}
function splitAt(s="",needle){const i=s.indexOf(needle);return i<0?[s,""]:[s.slice(0,i),s.slice(i)]} function paragraphs(s=""){return String(s).split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean)}
function address(c){return c.deliveryAddress||[c.buyer?.address,c.buyer?.cityStateZip].filter(Boolean).join("\n")} function buyer(b={}){return[b.name,b.company,b.address,b.cityStateZip].filter(Boolean).join("\n")} function seller(s={}){return[s.legalName||s.name,s.address,s.cityStateZip,s.phone,s.email].filter(Boolean).join("\n")}
function money(v,c="USD"){return new Intl.NumberFormat("en-US",{style:"currency",currency:c||"USD"}).format(Number(v||0))} function shortDate(v){if(!v)return"";const d=new Date(v);return `${d.getUTCMonth()+1}-${d.getUTCDate()}-${d.getUTCFullYear()}`} function sellerDate(v){if(!v)return"";const d=new Date(v);return `${d.getUTCDate()}-${d.getUTCMonth()+1}-${d.getUTCFullYear()}`} function longDate(v){if(!v)return"";return new Intl.DateTimeFormat("en-US",{timeZone:"UTC",month:"long",day:"numeric",year:"numeric"}).format(new Date(v)).replace(",","")}
function warrantyDate(v){return v?new Intl.DateTimeFormat("en-US",{timeZone:"UTC",month:"long",day:"numeric",year:"numeric"}).format(new Date(v)):""}
function isDefaultSeller(name=""){return /daniel\s+r\.?\s+petrov/i.test(name)}
function warrantySelections(w={}){const type=String(w.type||"").toLowerCase(),hasExplicit=[w.manufacturer,w.trial,w.other].some(value=>typeof value==="boolean");return hasExplicit?{manufacturer:w.manufacturer===true,trial:w.trial===true,other:w.other===true}:{manufacturer:type.includes("manufacturer"),trial:type.includes("30")||type.includes("trial"),other:Boolean(w.text)||(!type.includes("manufacturer")&&!type.includes("30")&&!type.includes("trial"))}}
function subheading(text=""){const value=String(text),period=value.match(/^([^.:]{2,80}\.)\s+(.+)$/s),colon=value.match(/^([A-Z][A-Z -]{2,30}:)\s+(.+)$/s),m=period||colon;return m?[m[1],m[2]]:["",value]}
