import test from "node:test";
import assert from "node:assert/strict";
import { calculateTotal, generatePublicToken, hashToken, sanitizeText, signingIntegrityPayload, stableHash, validateSignature, validateRequiredContract, validateSigningRequest, signatureMethod } from "../lib/contracts/security.js";
import { generateContractPdf } from "../lib/contracts/pdf.js";
import { buildSignedNotification, contractNotificationRecipients } from "../lib/contracts/notify.js";
import { contractPaperFit } from "../lib/contracts/responsive.js";

test("total calculation", () => assert.equal(calculateTotal(33600, 0, 650), 34250));
test("token generation and hash", () => { const a = generatePublicToken(), b = generatePublicToken(); assert.notEqual(a, b); assert.equal(hashToken(a), hashToken(a)); assert.notEqual(hashToken(a), a); });
test("sanitizes editable content", () => assert.equal(sanitizeText("<script>alert(1)</script>Hello\u0000"), "alert(1)Hello"));
test("validates signature bounds", () => { assert.equal(validateSignature([[[0, 0], [1, 1]]]), true); assert.equal(validateSignature([[[0, 0], [2, 1]]]), false); });
test("contract validation", () => assert.deepEqual(validateRequiredContract({ orderNumber: "A", buyer: { name: "Buyer", email: "b@example.com" }, equipment: { model: "120C" } }), []));
test("required contract fields", () => assert.ok(validateRequiredContract({}).length >= 3));
test("drawn signing requires strokes",()=>assert.equal(validateSigningRequest({signerName:"Jane Doe",acceptedTerms:true,typedSignatureConsent:true,signatureMethod:"drawn",signature:[]}).ok,false));
test("drawn signing succeeds",()=>assert.equal(validateSigningRequest({signerName:"Jane Doe",acceptedTerms:true,typedSignatureConsent:true,signatureMethod:"drawn",signature:[[[0,0],[1,1]]]}).ok,true));
test("typed consent requires its checkbox",()=>assert.equal(validateSigningRequest({signerName:"Jane Doe",acceptedTerms:true,typedSignatureConsent:false,signatureMethod:"typed_consent"}).ok,false));
test("typed consent succeeds without strokes",()=>assert.equal(validateSigningRequest({signerName:"Jane Doe",acceptedTerms:true,typedSignatureConsent:true,signatureMethod:"typed_consent"}).ok,true));
test("legacy stroke contract falls back to drawn",()=>assert.equal(signatureMethod({signature:[[[0,0],[1,1]]]}),"drawn"));
test("signature changes integrity hash",()=>{const a=signingIntegrityPayload({snapshotHash:"x",signerName:"J",signedAt:"2026-01-01",signatureMethod:"drawn",signature:[[[0,0],[1,1]]]});const b={...a,signature:[[[0,0],[.5,.5]]]};assert.notEqual(stableHash(a),stableHash(b))});
test("signed notification has both recipients, full details and stable identity",()=>{const c={...fixture(),_id:"contract-id",auditIp:"203.0.113.7",auditUserAgent:"Test Browser",buyer:{...fixture().buyer,name:"Jane <Doe>",phonePrimary:"555-0100",address:"1 Main St",cityStateZip:"Okemah, OK 74859"},equipment:{...fixture().equipment,serialNumber:"SERIAL-1",hours:"251"}},first=buildSignedNotification(c,{baseUrl:"https://example.com"}),second=buildSignedNotification(c,{baseUrl:"https://example.com"}),recipients=contractNotificationRecipients();assert.ok(recipients.includes("sales@sandwequipments.com"));assert.ok(recipients.includes("sara.mara.diaz@proton.me"));assert.equal(first.messageId,second.messageId);assert.match(first.subject,/TEST-1/);assert.match(first.text,/203\.0\.113\.7/);assert.match(first.text,/SERIAL-1/);assert.match(first.html,/Download signed PDF/);assert.match(first.html,/Jane &lt;Doe&gt;/);assert.doesNotMatch(first.html,/Jane <Doe>/)});
test("paper contracts auto-fit phones and tablets but stay full-size on desktop",()=>{assert.equal(contractPaperFit(390),(390-16)/816);assert.equal(contractPaperFit(768),(768-32)/816);assert.equal(contractPaperFit(1024),1)});
test("PDFs contain eight pages, vector declaration bullets and both seller signatures",()=>{const c=fixture(),signed=generateContractPdf(c,{signed:true}),unsigned=generateContractPdf(c,{signed:false}),binary=signed.toString("binary");assert.equal((binary.match(/\/Type \/Page\b/g)||[]).length,8);assert.equal((unsigned.toString("binary").match(/\/Type \/Page\b/g)||[]).length,8);assert.equal((binary.match(/ c f/g)||[]).length,c.templateSnapshot.buyerDeclarations.length);assert.equal((binary.match(/\/Im2 Do/g)||[]).length,2);assert.match(binary,/Buyer Representative Signature/);assert.match(binary,/August 21, 2026/);assert.doesNotMatch(unsigned.toString("binary"),/Electronically signed/)});
function fixture(){return{orderNumber:"TEST-1",orderDate:new Date("2026-01-01"),deliveryDate:new Date("2026-01-02"),buyer:{name:"Jane Doe",email:"jane@example.com"},seller:{name:"S & W Equipment",representativeName:"Daniel R. Petrov"},equipment:{make:"Case IH",model:"120C"},pricing:{subtotal:1,taxes:0,shipping:0,total:1,currency:"USD"},warranty:{type:"Manufacturer's Warranty + Other",manufacturer:true,trial:false,other:true,expiresAt:"2026-08-21",text:"Test"},templateSnapshot:{company:{name:"S & W Equipment"},sellerRepresentative:{name:"Daniel R. Petrov",signatureUrl:"/contract-seller-signature.png"},buyerDeclarations:["Received"],terms:Array.from({length:14},(_,i)=>({number:i+1,title:`Term ${i+1}`,body:"Contract wording."})),confirmationText:"Confirmed",witnessText:"Witness"},snapshotHash:"abc",integrityHash:"def",signedAt:new Date("2026-01-03"),signerName:"Jane Doe",signatureMethod:"typed_consent",typedSignatureConsent:true,acceptedTerms:true}}
