"use client";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import ContractDocument from "@/app/components/contracts/ContractDocument";
import SignatureRenderer from "@/app/components/contracts/SignatureRenderer";
import { TERMS_CONSENT_TEXT, TYPED_CONSENT_TEXT } from "@/lib/contracts/signature";
import { contractPaperFit, PAPER_SCREEN_WIDTH } from "@/lib/contracts/responsive";
import { contractSellerDisplayName } from "@/lib/contracts/company";

export default function ContractClient({ token }) {
  const router=useRouter(),canvas=useRef(null),documentContent=useRef(null),strokes=useRef([]),drawing=useRef(false);
  const [data,setData]=useState(null),[error,setError]=useState(""),[name,setName]=useState(""),[agreed,setAgreed]=useState(false),[electronicConsent,setElectronicConsent]=useState(false),[reuseSaved,setReuseSaved]=useState(false),[method,setMethod]=useState("drawn"),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[paperFit,setPaperFit]=useState({scale:1,height:0});
  useEffect(()=>{fetch(`/api/contracts/${encodeURIComponent(token)}`,{cache:"no-store"}).then(async r=>{const x=await r.json();if(x.state)router.replace(completedUrl(x.state,x.sellerDisplayName));else if(!r.ok)setError(x.error);else setData(x.contract)}).catch(()=>setError("The agreement could not be loaded."))},[token,router]);
  useEffect(()=>{const block=e=>{if(["INPUT","TEXTAREA"].includes(e.target?.tagName))return;if(e.type==="contextmenu"||((e.ctrlKey||e.metaKey)&&["p","s","c","u","i","j"].includes(e.key.toLowerCase())))e.preventDefault()};document.addEventListener("contextmenu",block);document.addEventListener("keydown",block);return()=>{document.removeEventListener("contextmenu",block);document.removeEventListener("keydown",block)}},[]);
  const layout=data?.linkTemplate||"paper";
  useEffect(()=>{if(layout!=="paper"||!documentContent.current)return;const content=documentContent.current,update=()=>{const scale=contractPaperFit(document.documentElement.clientWidth),height=content.scrollHeight;setPaperFit(current=>Math.abs(current.scale-scale)<.001&&current.height===height?current:{scale,height})};update();const observer=new ResizeObserver(update);observer.observe(content);window.addEventListener("resize",update);window.visualViewport?.addEventListener("resize",update);return()=>{observer.disconnect();window.removeEventListener("resize",update);window.visualViewport?.removeEventListener("resize",update)}},[layout,data]);
  const point=e=>{const r=canvas.current.getBoundingClientRect();return[Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))]};
  const start=e=>{e.preventDefault();drawing.current=true;strokes.current.push([point(e)]);canvas.current.setPointerCapture(e.pointerId)};
  const move=e=>{if(!drawing.current)return;const p=point(e),s=strokes.current.at(-1);s.push(p);const c=canvas.current,x=c.getContext("2d"),a=s.at(-2);x.lineWidth=2.2;x.lineCap="round";x.strokeStyle="#111";x.beginPath();x.moveTo(a[0]*c.width,a[1]*c.height);x.lineTo(p[0]*c.width,p[1]*c.height);x.stroke();setRevision(v=>v+1)};
  const clear=()=>{strokes.current=[];setRevision(v=>v+1);canvas.current?.getContext("2d").clearRect(0,0,canvas.current.width,canvas.current.height)};
  const eligible=name.trim().length>=2&&agreed&&electronicConsent&&(method==="typed_consent"||reuseSaved||strokes.current.some(s=>s.length>=2));
  const sellerDisplayName=contractSellerDisplayName(data);
  const sign=async()=>{if(!confirm("Your electronic signature will legally sign this agreement. Continue?"))return;setBusy(true);setError("");try{const r=await fetch(`/api/contracts/${encodeURIComponent(token)}/sign`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({signerName:name,acceptedTerms:agreed,typedSignatureConsent:electronicConsent,signatureMethod:method,signature:method==="drawn"&&!reuseSaved?strokes.current:undefined,reuseSavedSignature:reuseSaved,signatureConsentText:TYPED_CONSENT_TEXT})}),x=await r.json();if(!r.ok)throw new Error(x.error||"Signing failed.");router.replace(completedUrl("signed",sellerDisplayName))}catch(e){setError(e.message)}finally{setBusy(false)}};
  if(error&&!data)return <main className="grid min-h-screen place-items-center bg-zinc-950 p-6 text-white"><p>{error}</p></main>;if(!data)return <main className="grid min-h-screen place-items-center bg-zinc-950 text-white"><p>Loading confidential agreement...</p></main>;
  const stageStyle=layout==="paper"?{width:`${PAPER_SCREEN_WIDTH*paperFit.scale}px`,height:paperFit.height?`${paperFit.height*paperFit.scale}px`:"0px",opacity:paperFit.height?1:0}:undefined,contentStyle=layout==="paper"?{width:`${PAPER_SCREEN_WIDTH}px`,transform:`scale(${paperFit.scale})`}:undefined;
  return <main className={`contract-shell contract-shell--${layout} min-h-screen overflow-x-hidden bg-[#d7d7d7] py-4 text-black sm:py-8`}><div className={`contract-flow contract-flow--${layout}`}><div className={`contract-document-stage contract-document-stage--${layout}`} style={stageStyle}><div ref={documentContent} className="contract-document-scale" style={contentStyle}><ContractDocument contract={data} variant={layout}/></div></div><section className="contract-sign-panel relative z-10 rounded-xl bg-white shadow-xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#8b7018]">Final step</p><h2 className="mt-1 text-2xl font-bold">Electronic signature</h2>
    <label className="mt-5 block font-semibold">Full legal name<input value={name} onChange={e=>setName(e.target.value)} maxLength={200} className="mt-2 block w-full rounded-lg border border-zinc-400 p-3 font-sans"/></label>
    <fieldset className="mt-5"><legend className="font-bold">Signing method</legend><div className="mt-2 grid grid-cols-2 gap-2"><Method value="drawn" current={method} set={setMethod}>Draw signature</Method><Method value="typed_consent" current={method} set={setMethod}>Type and consent</Method></div></fieldset>
    {method==="drawn"?<div className="mt-5">{data.hasAuthorizedSavedSignature?<label className="mb-3 flex gap-3 rounded-lg border border-amber-300 bg-amber-50 p-4"><input type="checkbox" checked={reuseSaved} onChange={e=>setReuseSaved(e.target.checked)} className="h-5 w-5"/><span className="text-sm">Use the saved signature explicitly authorized by {sellerDisplayName} for this agreement.</span></label>:null}<p className="font-semibold">{reuseSaved?"Saved signature selected":"Draw signature"}</p>{!reuseSaved?<><canvas ref={canvas} width="800" height="220" onPointerDown={start} onPointerMove={move} onPointerUp={()=>drawing.current=false} onPointerCancel={()=>drawing.current=false} className="mt-2 h-44 w-full touch-none rounded-lg border-2 border-zinc-500 bg-white" aria-label="Signature drawing area"/><button type="button" onClick={clear} className="mt-2 text-sm underline">Clear Signature</button><div className="sr-only" key={revision}><SignatureRenderer method="drawn" strokes={strokes.current}/></div></>:null}</div>:<div className="mt-5 rounded-lg border bg-zinc-50 p-5 text-center"><SignatureRenderer method="typed_consent" typedName={name||"Your legal name"} className="mx-auto h-16 max-w-sm"/></div>}
    <label className="mt-5 flex gap-3 rounded-lg bg-zinc-50 p-4"><input type="checkbox" checked={agreed} onChange={e=>setAgreed(e.target.checked)} className="h-5 w-5 shrink-0"/><span className="text-sm">{TERMS_CONSENT_TEXT}</span></label>
    <label className="mt-3 flex gap-3 rounded-lg bg-zinc-50 p-4"><input type="checkbox" checked={electronicConsent} onChange={e=>setElectronicConsent(e.target.checked)} className="h-5 w-5 shrink-0"/><span className="text-sm">{TYPED_CONSENT_TEXT}</span></label>
    {error?<p role="alert" className="mt-4 text-red-700">{error}</p>:null}<button type="button" onClick={sign} disabled={busy||!eligible} className="mt-6 w-full rounded-lg bg-black px-6 py-4 font-bold text-white hover:bg-[#c9a227] hover:text-black disabled:opacity-40">{busy?"Signing...":"Sign agreement"}</button>
  </section></div><div className="print-only">Printing this confidential document is not permitted.</div></main>;
}
function Method({value,current,set,children}){return <label className={`cursor-pointer rounded-lg border-2 p-3 text-center font-bold ${current===value?"border-[#c9a227] bg-amber-50":"border-zinc-300"}`}><input type="radio" name="signatureMethod" value={value} checked={current===value} onChange={()=>set(value)} className="sr-only"/>{children}</label>}
function completedUrl(state,sellerDisplayName){const params=new URLSearchParams({state,seller:String(sellerDisplayName||"").slice(0,200)});return `/contract/completed?${params}`}
