"use client";
import {useEffect,useMemo,useState} from "react";
import SignatureRenderer from "@/app/components/contracts/SignatureRenderer";

export default function ClientSignaturesAdmin(){
  const[sellers,setSellers]=useState([]),[clients,setClients]=useState([]),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const load=async(showLoading=true)=>{if(showLoading)setLoading(true);setError("");try{const options={cache:"no-store"},[sellerResponse,clientResponse]=await Promise.all([fetch("/api/admin/contract-assets",options),fetch("/api/admin/client-signatures",options)]),[sellerData,clientData]=await Promise.all([safeJson(sellerResponse),safeJson(clientResponse)]);if(!sellerResponse.ok)throw new Error(sellerData.error||"Seller signatures could not be loaded.");if(!clientResponse.ok)throw new Error(clientData.error||"Client signatures could not be loaded.");setSellers(sellerData.items||[]);setClients(clientData.items||[])}catch(e){setError(e.message)}finally{if(showLoading)setLoading(false)}};
  useEffect(()=>{load()},[]);
  const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?clients.filter(x=>[x.clientName,x.clientEmail,x.typedName,x.sourceContractId].some(v=>String(v||"").toLowerCase().includes(q))):clients},[clients,query]);
  const setDefault=async signature=>{setBusy(signature._id);setError("");setNotice("");try{const r=await fetch("/api/admin/contract-assets",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"set-default",url:signature.url,name:signature.name})}),x=await safeJson(r);if(!r.ok)throw new Error(x.error||"Default signature could not be changed.");setSellers(items=>items.map(item=>({...item,isDefault:item.url===signature.url})));setNotice(`${signature.name} is now the default seller signature for new contracts.`)}catch(e){setError(e.message)}finally{setBusy("")}};
  const deleteSeller=async signature=>{if(signature.builtin||!confirm(`Delete the saved seller signature for ${signature.name}? Existing contracts will keep their copy.`))return;setBusy(signature._id);setError("");setNotice("");try{const r=await fetch("/api/admin/contract-assets",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"delete",id:signature._id})}),x=await safeJson(r);if(!r.ok)throw new Error(x.error||"Signature could not be deleted.");await load(false);setNotice("Seller signature deleted from Saved signatures.")}catch(e){setError(e.message)}finally{setBusy("")}};
  const revoke=async id=>{if(!confirm("Revoke this saved client signature? Existing signed contracts will not change."))return;setBusy(id);setError("");try{const r=await fetch(`/api/admin/client-signatures/${id}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"revoke"})}),x=await safeJson(r);if(!r.ok)throw new Error(x.error||"Revocation failed.");setClients(items=>items.map(item=>item._id===id?{...item,revokedAt:new Date().toISOString()}:item));setNotice("Client signature revoked.")}catch(e){setError(e.message)}finally{setBusy("")}};
  const deleteClient=async signature=>{if(!confirm(`Delete the saved signature for ${signature.clientName}? The signed contract remains unchanged, but this signature can no longer be reused.`))return;setBusy(signature._id);setError("");setNotice("");try{const r=await fetch(`/api/admin/client-signatures/${signature._id}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"delete"})}),x=await safeJson(r);if(!r.ok)throw new Error(x.error||"Signature could not be deleted.");await load(false);setNotice("Client signature deleted from Saved signatures.")}catch(e){setError(e.message)}finally{setBusy("")}};

  if(loading)return <div className="rounded-2xl border bg-white p-12 text-center text-zinc-500 shadow-sm">Loading all signatures...</div>;
  return <div className="space-y-8">
    {error?<p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-800">{error}</p>:null}{notice?<p role="status" className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-amber-900">{notice}</p>:null}

    <section className="rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm md:p-6">
      <div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-2xl font-bold">Seller / employee signatures</h2><p className="mt-1 text-sm text-zinc-600">The default signature is loaded automatically when a new contract is created. Saving a contract with another seller signature makes that one the latest default.</p></div><span className="rounded-full bg-zinc-100 px-3 py-1.5 text-sm font-semibold">{sellers.length} signatures</span></div>
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{sellers.map(signature=><article key={signature._id} className={`relative overflow-hidden rounded-2xl border-2 bg-white ${signature.isDefault?"border-[#c9a227] shadow-md":"border-zinc-200"}`}>
        {signature.isDefault?<span className="absolute left-3 top-3 z-10 rounded-full bg-[#c9a227] px-2.5 py-1 text-[11px] font-bold text-black">DEFAULT</span>:null}{!signature.builtin?<DeleteButton label={`Delete seller signature for ${signature.name}`} disabled={!!busy} onClick={()=>deleteSeller(signature)}/>:null}
        <div className="flex h-36 items-center justify-center bg-zinc-50 p-5"><img src={signature.url} alt={`Signature of ${signature.name}`} className="max-h-24 max-w-full object-contain"/></div>
        <div className="border-t border-zinc-100 p-4"><h3 className="font-bold">{signature.name}</h3><p className="mt-1 text-xs text-zinc-500">{signature.builtin?"Included with the contract template":`Used ${signature.usageCount||0} time(s)`}</p>{signature.lastUsedAt?<p className="mt-1 text-xs text-zinc-500">Last used {date(signature.lastUsedAt)}</p>:null}<button type="button" disabled={signature.isDefault||!!busy} onClick={()=>setDefault(signature)} className="mt-3 w-full rounded-lg border border-zinc-300 px-3 py-2 text-sm font-bold transition hover:border-[#c9a227] hover:bg-amber-50 disabled:cursor-default disabled:opacity-50">{signature.isDefault?"Current default":busy===signature._id?"Saving...":"Set as default"}</button></div>
      </article>)}</div>
    </section>

    <section className="rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm md:p-6">
      <div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-2xl font-bold">Client signatures</h2><p className="mt-1 text-sm text-zinc-600">All saved client signatures are shown directly. Reuse still requires exact email matching and explicit client consent.</p></div><span className="rounded-full bg-zinc-100 px-3 py-1.5 text-sm font-semibold">{clients.length} signatures</span></div>
      <label className="mb-5 block"><span className="mb-1.5 block text-xs font-bold uppercase tracking-wide text-zinc-500">Filter signatures</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, email or contract ID" className="admin-input mt-0"/></label>
      {filtered.length?<div className="grid gap-4 md:grid-cols-2">{filtered.map(signature=><article key={signature._id} className={`relative overflow-hidden rounded-2xl border ${signature.revokedAt?"border-red-200 bg-red-50/30":"border-zinc-200 bg-white"}`}><DeleteButton label={`Delete saved signature for ${signature.clientName}`} disabled={!!busy} onClick={()=>deleteClient(signature)}/><div className="flex h-32 items-center justify-center border-b border-zinc-100 bg-zinc-50 p-4"><SignatureRenderer method={signature.signatureType} strokes={signature.strokeData} typedName={signature.typedName||signature.clientName} className="h-24 w-full max-w-sm text-black"/></div><div className="p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold">{signature.clientName}</h3><p className="text-sm text-zinc-600">{signature.clientEmail}</p></div>{signature.revokedAt?<span className="rounded-full bg-red-100 px-2.5 py-1 text-[11px] font-bold text-red-800">REVOKED</span>:<span className="rounded-full bg-emerald-100 px-2.5 py-1 text-[11px] font-bold text-emerald-800">ACTIVE</span>}</div><dl className="mt-3 grid grid-cols-2 gap-2 text-xs"><div><dt className="font-bold text-zinc-500">Type</dt><dd>{signature.signatureType==="typed_consent"?"Typed consent":"Drawn"}</dd></div><div><dt className="font-bold text-zinc-500">Uses</dt><dd>{signature.usageCount||0}</dd></div><div className="col-span-2"><dt className="font-bold text-zinc-500">Source contract</dt><dd className="break-all">{signature.sourceContractId}</dd></div><div><dt className="font-bold text-zinc-500">Created</dt><dd>{date(signature.createdAt)}</dd></div><div><dt className="font-bold text-zinc-500">Last used</dt><dd>{signature.lastUsedAt?date(signature.lastUsedAt):"Never"}</dd></div></dl>{!signature.revokedAt?<button type="button" disabled={!!busy} onClick={()=>revoke(signature._id)} className="mt-4 rounded-lg border border-red-200 px-3 py-2 text-sm font-semibold text-red-700 hover:bg-red-50 disabled:opacity-50">{busy===signature._id?"Revoking...":"Revoke saved signature"}</button>:null}</div></article>)}</div>:<div className="rounded-xl border border-dashed border-zinc-300 p-10 text-center text-zinc-500">No signatures match this filter.</div>}
    </section>
  </div>
}

function date(value){return new Intl.DateTimeFormat("en-GB",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}
function DeleteButton({label,onClick,disabled}){return <button type="button" aria-label={label} title={label} disabled={disabled} onClick={onClick} className="absolute right-3 top-3 z-20 grid h-7 w-7 place-items-center rounded-full border border-red-200 bg-white text-lg font-bold leading-none text-red-700 shadow-sm transition hover:bg-red-600 hover:text-white disabled:cursor-not-allowed disabled:opacity-40">×</button>}
async function safeJson(response){const text=await response.text();if(!text)throw new Error(`Server returned an empty response (${response.status}).`);try{return JSON.parse(text)}catch{throw new Error(`Server returned an invalid response (${response.status}).`)}}
