"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";

const statuses=["","draft","ready","viewed","signed","revoked","expired"];
const badge={draft:"border-zinc-200 bg-zinc-100 text-zinc-700",ready:"border-blue-200 bg-blue-50 text-blue-800",viewed:"border-amber-200 bg-amber-50 text-amber-900",signed:"border-emerald-200 bg-emerald-50 text-emerald-800",revoked:"border-red-200 bg-red-50 text-red-800",expired:"border-orange-200 bg-orange-50 text-orange-900"};
const PAGE_SIZE=10;

export default function ContractAdmin(){
  const [items,setItems]=useState([]),[q,setQ]=useState(""),[status,setStatus]=useState(""),[page,setPage]=useState(1),[pages,setPages]=useState(1),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[workingId,setWorkingId]=useState(""),[notice,setNotice]=useState(""),[error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await fetch(`/api/admin/contracts?q=${encodeURIComponent(q)}&status=${status}&page=${page}&limit=${PAGE_SIZE}`,{cache:"no-store"}),x=await safeJson(r);if(!r.ok)throw new Error(x.error||"Contracts could not be loaded.");setItems(x.items||[]);setPages(x.pages||1);setTotal(x.total||0)}catch(e){setItems([]);setTotal(0);setError(e.message)}finally{setLoading(false)}},[q,status,page]);
  useEffect(()=>{const timer=setTimeout(load,250);return()=>clearTimeout(timer)},[load]);
  const action=async(contract,type)=>{const id=contract._id,number=contract.orderNumber||"Draft";
    if(type==="deactivate"&&!confirm("Deactivate this signing link? The client will no longer be able to access it, but the contract will remain in the table."))return;
    if(type==="regenerate"){const viewed=contract.status==="viewed"?" The client has already opened the current link.":"",answer=prompt(`Create a new active signing link for contract #${number}?${viewed}\n\nThe link already sent to the client will stop working immediately. Type REPLACE to continue.`);if(answer?.trim().toUpperCase()!=="REPLACE"){setNotice("No changes were made. The current client link is still valid.");return}}
    if(type==="activate"&&!confirm(`Activate contract #${number} with a new signing link? The new link will be copied to your clipboard.`))return;
    if(type==="unsign"){const answer=prompt(`Remove the signature from contract #${number}?\n\nThe signed PDF will stop being available and the original client link will become active again. Any notification email already sent cannot be recalled. Type UNSIGN to continue.`);if(answer?.trim().toUpperCase()!=="UNSIGN"){setNotice("No changes were made. The contract remains signed.");return}}
    if(type==="delete"){const signedWarning=contract.status==="signed"?" This contract is signed and its signed PDF will no longer be available.":"";if(!confirm(`Permanently delete contract #${number}?${signedWarning} This action cannot be undone.`))return}
    const requestAction=async(action,extra={})=>{const response=await fetch(`/api/admin/contracts/${id}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...extra})});return{response,data:await safeJson(response)}};
    setNotice("");setError("");setWorkingId(id);try{
      const serverAction=type==="deactivate"?"revoke":type==="activate"?"regenerate":type,extra=["regenerate","activate"].includes(type)?{confirmReplace:true}:{};
      let effectiveType=type,result=type==="delete"?{response:await fetch(`/api/admin/contracts/${id}`,{method:"DELETE"})}:await requestAction(serverAction,extra);
      if(!result.data)result.data=await safeJson(result.response);
      const x=result.data;if(!result.response.ok)throw new Error(x.error||"Action failed.");if(type==="delete"){setItems(current=>current.filter(item=>item._id!==id));setTotal(current=>Math.max(0,current-1));setNotice(`Contract #${number} was deleted.`);if(page>1&&items.length===1)setPage(current=>current-1);else await load()}else if(x.publicUrl){await navigator.clipboard.writeText(x.publicUrl);const messages={regenerate:"Replacement link copied. The previous client link is now invalid.",activate:"The contract was activated with a new signing link, which was copied.","copy-active":"Active signing link copied. The client link remains unchanged.","copy-signed":"Signed contract link copied. Opening it shows that this agreement has already been signed."};setNotice(effectiveType==="copy-active"&&x.alias?"Previously stored access link copied. No link was created or changed.":effectiveType==="copy-signed"&&x.archived?"Previously stored signed-status link copied. No link was created or changed.":(messages[effectiveType]||"Signing link copied to the clipboard."));if(!["copy-active","copy-signed"].includes(effectiveType))await load()}else if(x.id)window.location.assign(`/admin/contracts/${x.id}/edit`);else{setNotice(type==="deactivate"?"Signing link deactivated. The contract remains available in the table.":type==="unsign"?`Signature removed. The original client link is active again.${x.notificationWasSent?" The previous notification email cannot be recalled.":""}`:type==="retry-notification"?"Signed-contract email sent successfully to both recipients.":"Action completed.");await load()}
    }catch(e){setError(e.message)}finally{setWorkingId("")}};
  const setLinkTemplate=async(id,template)=>{setNotice("");setError("");setItems(current=>current.map(c=>c._id===id?{...c,linkTemplate:template}:c));try{const r=await fetch(`/api/admin/contracts/${id}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"set-link-template",template})}),x=await safeJson(r);if(!r.ok)throw new Error(x.error||"Template could not be changed.");setNotice(`Link template changed to ${template}.`)}catch(e){setError(e.message);load()}};

  return <section aria-label="Contract management">
    <div className="mb-5 rounded-2xl border border-zinc-200 bg-white p-4 shadow-sm md:p-5">
      <div className="grid gap-3 lg:grid-cols-[minmax(280px,1fr)_210px_auto]">
        <label><span className="mb-1.5 block text-xs font-bold uppercase tracking-wide text-zinc-500">Search by contract, buyer or equipment</span><input aria-label="Search by contract, buyer or equipment" placeholder="Contract number, buyer name, equipment or serial number" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} className="admin-input mt-0"/></label>
        <label><span className="mb-1.5 block text-xs font-bold uppercase tracking-wide text-zinc-500">Status</span><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}} className="admin-input mt-0">{statuses.map(s=><option key={s} value={s}>{s?human(s):"All statuses"}</option>)}</select></label>
        <Link href="/admin/contracts/new" className="self-end rounded-xl bg-[#c9a227] px-6 py-3 text-center font-bold text-black shadow-sm transition hover:bg-[#b18d1e] hover:shadow-md">+ Create Contract</Link>
      </div>
      <div className="mt-4 flex flex-wrap items-center justify-between gap-2 border-t border-zinc-100 pt-4 text-sm"><span className="font-medium text-zinc-700">{loading?"Loading contracts...":<>{total?<>Showing <b className="text-zinc-950">{(page-1)*PAGE_SIZE+1}–{Math.min(page*PAGE_SIZE,total)}</b> of </>:null}<b className="text-lg text-zinc-950">{total}</b> {total===1?"contract":"contracts"} · {PAGE_SIZE} per page</>}</span>{(q||status)&&<button type="button" onClick={()=>{setQ("");setStatus("");setPage(1)}} className="rounded-lg px-3 py-1.5 font-semibold text-[#846a18] hover:bg-amber-50">Clear filters</button>}</div>
    </div>
    {notice?<p role="status" className="mb-4 rounded-xl border border-amber-200 bg-amber-50 p-3.5 text-sm font-medium text-amber-900 shadow-sm">{notice}</p>:null}
    {error?<p role="alert" className="mb-4 rounded-xl border border-red-200 bg-red-50 p-3.5 text-sm font-medium text-red-800 shadow-sm">{error}</p>:null}

    <div className="hidden overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-sm lg:block"><div className="overflow-x-auto"><table className="w-full min-w-[1080px] text-left text-sm">
      <thead className="border-b border-zinc-200 bg-zinc-950 text-white"><tr>{["Contract","Buyer","Equipment","Total","Timeline","Signature","Link view","Actions"].map(x=><th key={x} className="px-4 py-3.5 text-[11px] font-bold uppercase tracking-[.12em]">{x}</th>)}</tr></thead>
      <tbody className="divide-y divide-zinc-100">{loading?<TableMessage text="Loading contracts..."/>:items.length===0?<TableMessage text="No contracts match these filters."/>:items.map(c=><ContractRow key={c._id} contract={c} onAction={action} onTemplate={setLinkTemplate} busy={workingId===c._id}/>)}</tbody>
    </table></div></div>

    <div className="grid gap-4 lg:hidden">{loading?<MobileMessage text="Loading contracts..."/>:items.length===0?<MobileMessage text="No contracts match these filters."/>:items.map(c=><ContractCard key={c._id} contract={c} onAction={action} onTemplate={setLinkTemplate} busy={workingId===c._id}/>)}</div>
    <div className="mt-5 flex items-center justify-between rounded-2xl border border-zinc-200 bg-white px-4 py-3 shadow-sm"><button disabled={page<=1||loading} onClick={()=>setPage(p=>p-1)} className="rounded-lg border border-zinc-300 px-4 py-2 text-sm font-semibold transition hover:border-[#c9a227] disabled:cursor-not-allowed disabled:opacity-40">← Previous</button><span className="rounded-full bg-zinc-100 px-3 py-1.5 text-sm font-semibold">Page {page} of {pages}</span><button disabled={page>=pages||loading} onClick={()=>setPage(p=>p+1)} className="rounded-lg border border-zinc-300 px-4 py-2 text-sm font-semibold transition hover:border-[#c9a227] disabled:cursor-not-allowed disabled:opacity-40">Next →</button></div>
  </section>
}

function ContractRow({contract:c,onAction,onTemplate,busy}){return <tr className="align-top transition-colors hover:bg-amber-50/50"><td className="px-4 py-4"><Link href={`/admin/contracts/${c._id}`} className="text-base font-bold text-zinc-950 hover:text-[#846a18] hover:underline">#{c.orderNumber||"Draft"}</Link><div className="mt-2"><StatusBadge value={c.status}/></div></td><td className="px-4 py-4"><p className="font-semibold text-zinc-900">{c.buyer?.name||"—"}</p><p className="mt-1 max-w-48 truncate text-xs text-zinc-500">{c.buyer?.email||"No email"}</p><p className="mt-0.5 text-xs text-zinc-500">{c.buyer?.phonePrimary||"No phone"}</p></td><td className="px-4 py-4"><p className="max-w-56 font-medium text-zinc-900">{[c.equipment?.year,c.equipment?.make,c.equipment?.model].filter(Boolean).join(" ")||"—"}</p>{c.equipment?.serialNumber?<p className="mt-1 text-xs text-zinc-500">S/N {c.equipment.serialNumber}</p>:null}</td><td className="whitespace-nowrap px-4 py-4 text-base font-bold text-zinc-950">{money(c.pricing?.total,c.pricing?.currency)}</td><td className="whitespace-nowrap px-4 py-4 text-xs text-zinc-600"><p><span className="font-semibold text-zinc-800">Created</span><br/>{fmt(c.createdAt)}</p><p className="mt-2"><span className="font-semibold text-zinc-800">Signed</span><br/>{c.signedAt?fmt(c.signedAt):"—"}</p></td><td className="px-4 py-4"><SignatureBadge contract={c}/></td><td className="px-4 py-4"><TemplatePicker contract={c} onTemplate={onTemplate}/></td><td className="px-4 py-4"><ContractActions contract={c} onAction={onAction} busy={busy}/></td></tr>}

function ContractCard({contract:c,onAction,onTemplate,busy}){return <article className="overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-sm"><div className="flex items-start justify-between gap-3 border-b border-zinc-100 bg-zinc-50 px-4 py-3"><div><Link href={`/admin/contracts/${c._id}`} className="text-lg font-bold hover:text-[#846a18]">#{c.orderNumber||"Draft"}</Link><p className="mt-1 text-sm font-medium text-zinc-700">{c.buyer?.name||"—"}</p></div><StatusBadge value={c.status}/></div><div className="grid grid-cols-2 gap-4 p-4 text-sm"><Info label="Equipment" value={[c.equipment?.year,c.equipment?.make,c.equipment?.model].filter(Boolean).join(" ")||"—"}/><Info label="Total" value={money(c.pricing?.total,c.pricing?.currency)} strong/><Info label="Created" value={fmt(c.createdAt)}/><Info label="Signed" value={c.signedAt?fmt(c.signedAt):"—"}/><div><Label>Signature</Label><SignatureBadge contract={c}/></div><div><Label>Link view</Label><TemplatePicker contract={c} onTemplate={onTemplate}/></div></div><div className="border-t border-zinc-100 bg-zinc-50 p-4"><ContractActions contract={c} onAction={onAction} busy={busy}/></div></article>}

function ContractActions({contract:c,onAction,busy}){const active=["ready","viewed"].includes(c.status),inactive=["revoked","expired"].includes(c.status),signed=c.status==="signed";return <div className="flex max-w-64 flex-wrap gap-2"><ActionLink href={`/admin/contracts/${c._id}`} primary>View</ActionLink>{signed?<ActionLink href={`/admin/contracts/${c._id}/signed`}>Signed contract</ActionLink>:<ActionLink href={`/admin/contracts/${c._id}/edit`}>Edit</ActionLink>}{signed?<><ActionButton disabled={busy} title="Copies the client link used for this signed contract" onClick={()=>onAction(c,"copy-signed")}>Copy signed link</ActionButton><ActionButton disabled={busy} danger title="Removes the incorrect signature and reactivates the original client link" onClick={()=>onAction(c,"unsign")}>Unsign</ActionButton></>:null}<ActionButton disabled={busy} onClick={()=>onAction(c,"duplicate")}>Duplicate</ActionButton>{active&&<><ActionButton disabled={busy} title="Copies the current active client link without changing it" onClick={()=>onAction(c,"copy-active")}>Copy active link</ActionButton><ActionButton disabled={busy} danger title="Invalidates the current client link and creates a replacement" onClick={()=>onAction(c,"regenerate")}>Replace signing link…</ActionButton><ActionButton disabled={busy} danger onClick={()=>onAction(c,"deactivate")}>Deactivate link</ActionButton></>}{inactive?<ActionButton disabled={busy} title="Creates and copies a new signing link" onClick={()=>onAction(c,"activate")}>Activate with new link</ActionButton>:null}{signed&&c.notification?.status==="failed"?<ActionButton disabled={busy} title="Retries the failed signed-contract email once" onClick={()=>onAction(c,"retry-notification")}>Retry email</ActionButton>:null}<ActionButton disabled={busy} danger onClick={()=>onAction(c,"delete")}>{busy?"Working...":"Delete"}</ActionButton></div>}
function TemplatePicker({contract:c,onTemplate}){const template=c.linkTemplate||"paper";return <div className="inline-flex overflow-hidden rounded-lg border border-zinc-300 bg-white shadow-sm"><TemplateButton active={template==="site"} onClick={()=>onTemplate(c._id,"site")}>Site</TemplateButton><TemplateButton active={template==="paper"} onClick={()=>onTemplate(c._id,"paper")}>Paper</TemplateButton></div>}
function StatusBadge({value}){return <span className={`inline-flex items-center rounded-full border px-2.5 py-1 text-[11px] font-bold ${badge[value]||badge.draft}`}><span className="mr-1.5 text-[8px]">●</span>{human(value||"draft")}</span>}
function SignatureBadge({contract:c}){const text=c.signatureMethod==="typed_consent"?"Typed consent":c.signedAt?"Drawn signature":"Not signed",style=c.signatureMethod==="typed_consent"?"border-purple-200 bg-purple-50 text-purple-800":c.signedAt?"border-sky-200 bg-sky-50 text-sky-800":"border-zinc-200 bg-zinc-50 text-zinc-600";return <span className={`inline-flex whitespace-nowrap rounded-full border px-2.5 py-1 text-[11px] font-bold ${style}`}>{text}</span>}
function TableMessage({text}){return <tr><td colSpan="8" className="p-16 text-center text-zinc-500">{text}</td></tr>}
function MobileMessage({text}){return <div className="rounded-2xl border border-zinc-200 bg-white p-12 text-center text-zinc-500 shadow-sm">{text}</div>}
function ActionLink({href,children,primary=false}){return <Link href={href} className={`rounded-lg border px-3 py-1.5 text-xs font-semibold transition ${primary?"border-zinc-950 bg-zinc-950 text-white hover:border-[#c9a227] hover:bg-[#c9a227] hover:text-black":"border-zinc-300 bg-white hover:border-[#c9a227] hover:bg-amber-50"}`}>{children}</Link>}
function ActionButton({onClick,children,danger=false,disabled=false,title}){return <button type="button" onClick={onClick} disabled={disabled} title={title} className={`rounded-lg border px-3 py-1.5 text-xs font-semibold transition disabled:cursor-not-allowed disabled:opacity-50 ${danger?"border-red-200 bg-white text-red-700 hover:bg-red-50":"border-zinc-300 bg-white hover:border-[#c9a227] hover:bg-amber-50"}`}>{children}</button>}
function TemplateButton({active,onClick,children}){return <button type="button" aria-pressed={active} onClick={onClick} className={`px-3 py-1.5 text-xs font-bold transition ${active?"bg-[#c9a227] text-black":"bg-white text-zinc-600 hover:bg-zinc-100"}`}>{children}</button>}
function Info({label,value,strong=false}){return <div><Label>{label}</Label><p className={strong?"font-bold text-zinc-950":"font-medium text-zinc-800"}>{value}</p></div>}
function Label({children}){return <span className="mb-1 block text-[10px] font-bold uppercase tracking-wide text-zinc-500">{children}</span>}
function human(v=""){const labels={revoked:"Deactivated",ready:"Active"};return labels[v]||v.charAt(0).toUpperCase()+v.slice(1)}
function fmt(v){return v?new Intl.DateTimeFormat("en-GB",{dateStyle:"medium"}).format(new Date(v)):"—"}
function money(v,c="USD"){return new Intl.NumberFormat("en-US",{style:"currency",currency:c||"USD"}).format(Number(v||0))}
async function safeJson(response){const text=await response.text();if(!text)throw new Error(`Server returned an empty response (${response.status}).`);try{return JSON.parse(text)}catch{throw new Error(`Server returned an invalid response (${response.status}).`)}}
