"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";

const blank={orderNumber:"",orderDate:"",deliveryDate:"",buyer:{name:"",company:"",address:"",cityStateZip:"",phonePrimary:"",phoneSecondary:"",email:"",contact:""},deliveryAddress:"",equipment:{make:"",model:"",year:"",serialNumber:"",hours:"",description:"",images:[]},pricing:{subtotal:0,taxes:0,shipping:0,total:0,currency:"USD",totalOverridden:false},seller:{name:"S & W Equipment",legalName:"Gently Auto Sales LLC DBA S & W Equipment",address:"715 W Coplin St",cityStateZip:"Okemah, OK 74859",phone:"(405) 501-7617",email:"sales@sandwequipments.com",representativeName:""},deliveryChecks:{},warranty:{type:"Other",text:"",expiresAt:"",manufacturer:false,trial:false,other:true},linkExpiresAt:""};
const DELIVERY_CHECKS=[
  ["deliveryCompleted","Delivery completed","Confirm the equipment was delivered or collected."],
  ["buyerInspected","Delivery inspection completed by Buyer","The buyer had the opportunity to inspect the equipment."],
  ["manualsGiven","Applicable Owner’s and Safety Manuals given","Required manuals were provided when applicable."],
  ["safetyExplained","Use and safety procedures explained","Operating and safety guidance was explained."],
  ["maintenanceExplained","Maintenance procedures explained","Routine maintenance guidance was explained."],
];

export default function ContractForm({id}){
  const router=useRouter(),[form,setForm]=useState(blank),[template,setTemplate]=useState(null),[sellerSignatures,setSellerSignatures]=useState([]),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState(""),[link,setLink]=useState("");
  useEffect(()=>{Promise.all([fetch("/api/admin/contract-template").then(safeJson),id?fetch(`/api/admin/contracts/${id}`).then(safeJson):null,fetch("/api/admin/contract-assets",{cache:"no-store"}).then(safeJson)]).then(([t,c,assets])=>{setTemplate(c?.templateSnapshot||t);setSellerSignatures(assets?.items||[]);if(c)setForm({...blank,...c,buyer:{...blank.buyer,...c.buyer},equipment:{...blank.equipment,...c.equipment},pricing:{...blank.pricing,...c.pricing},seller:{...blank.seller,...c.seller},deliveryChecks:c.deliveryChecks||{},warranty:{...blank.warranty,...normalizeWarranty(c.warranty||{})},orderDate:short(c.orderDate),deliveryDate:short(c.deliveryDate),linkExpiresAt:local(c.linkExpiresAt)});else setForm(current=>({...current,seller:sellerDefaults(t)}))}).catch(e=>setError(e.message))},[id]);
  const set=(group,key,value)=>setForm(f=>group?{...f,[group]:{...f[group],[key]:value}}:{...f,[key]:value});
  const toggleWarranty=(key,checked)=>setForm(f=>{const warranty={...f.warranty,[key]:checked},selected=[["manufacturer","Manufacturer's Warranty"],["trial","30-day trial"],["other","Other"]].filter(([name])=>warranty[name]).map(([,label])=>label);return{...f,warranty:{...warranty,type:selected.join(" + ")}}});
  const total=Number(form.pricing.subtotal||0)+Number(form.pricing.taxes||0)+Number(form.pricing.shipping||0);
  const uploadAsset=async(file,kind)=>{if(!file)return;setUploading(kind);setError("");try{const representativeName=template.sellerRepresentative?.name||form.seller.representativeName||"Seller Representative",body=new FormData();body.append("file",file);body.append("kind",kind);if(kind==="signature")body.append("representativeName",representativeName);const r=await fetch("/api/admin/contract-assets",{method:"POST",body}),x=await safeJson(r);if(!r.ok)throw new Error(x.error||"Upload failed.");setTemplate(t=>kind==="logo"?{...t,logoUrl:x.url}:{...t,sellerRepresentative:{...t.sellerRepresentative,signatureUrl:x.url}});if(kind==="signature")setSellerSignatures(items=>[{_id:x.publicId,url:x.url,name:representativeName,label:"New upload",usageCount:0,isDefault:false,builtin:false},...items.filter(item=>item.url!==x.url)]);setNotice(`${kind==="logo"?"Logo":"Signature"} uploaded and selected. It will be saved with this contract${kind==="signature"?" and printed in both PDF signature sections":""}.`)}catch(e){setError(e.message)}finally{setUploading("")}};
  const selectSellerSignature=signature=>{setTemplate(t=>({...t,sellerRepresentative:{...t.sellerRepresentative,name:signature.name||t.sellerRepresentative?.name||"Seller Representative",signatureUrl:signature.url}}));setNotice(`${signature.name} selected. Save the contract to use this signature in both places in the PDF.`)};
  const saveSellerDefaults=async()=>{setBusy(true);setError("");setNotice("");try{const nextTemplate={...template,company:{...template.company,name:form.seller.name,legalName:form.seller.legalName,address:form.seller.address,cityStateZip:form.seller.cityStateZip,phone:form.seller.phone,email:form.seller.email},sellerRepresentative:{...template.sellerRepresentative,name:template.sellerRepresentative?.name||form.seller.representativeName||"Seller Representative"}},r=await fetch("/api/admin/contract-template",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(nextTemplate)}),x=await safeJson(r);if(!r.ok)throw new Error(x.error||"Seller defaults could not be saved.");setTemplate(x.template);setSellerSignatures(items=>items.map(item=>({...item,isDefault:item.url===x.template.sellerRepresentative?.signatureUrl})));setNotice("Seller company details and signature saved as defaults for future contracts.")}catch(e){setError(e.message)}finally{setBusy(false)}};
  const saveBranding=async()=>{setBusy(true);setError("");try{const r=await fetch("/api/admin/contract-template",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(template)}),x=await safeJson(r);if(!r.ok)throw new Error(x.error||"Branding could not be saved.");setTemplate(x.template);setNotice("Branding, seller signature, and wording will be reused for new contracts.")}catch(e){setError(e.message)}finally{setBusy(false)}};
  const save=async(generate=false)=>{setBusy(true);setError("");try{const payload={...form,templateSnapshot:template,generateLink:generate,pricing:{...form.pricing,total:form.pricing.totalOverridden?Number(form.pricing.total):total}},r=await fetch(id?`/api/admin/contracts/${id}`:"/api/admin/contracts",{method:id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),x=await safeJson(r);if(!r.ok)return setError([x.error,...(x.errors||[])].join(" "));if(x.publicUrl)setLink(x.publicUrl);else router.push("/admin/contracts")}catch(e){setError(e.message||"The contract could not be saved.")}finally{setBusy(false)}};
  const publish=async()=>{setBusy(true);setError("");setNotice("");try{const payload={...form,templateSnapshot:template,pricing:{...form.pricing,total:form.pricing.totalOverridden?Number(form.pricing.total):total}},saveResponse=await fetch(`/api/admin/contracts/${id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),saved=await safeJson(saveResponse);if(!saveResponse.ok)throw new Error([saved.error,...(saved.errors||[])].filter(Boolean).join(" "));const publishResponse=await fetch(`/api/admin/contracts/${id}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"generate"})}),published=await safeJson(publishResponse);if(!publishResponse.ok)throw new Error(published.error||"The draft could not be published.");setForm(current=>({...current,status:"ready"}));setLink(published.publicUrl||"");if(published.publicUrl)navigator.clipboard.writeText(published.publicUrl).catch(()=>{});setNotice("Contract published. The active signing link was copied and will remain available below.")}catch(e){setError(e.message||"The draft could not be published.")}finally{setBusy(false)}};
  const duplicateAsDraft=async()=>{setBusy(true);setError("");setNotice("");try{const payload={...form,templateSnapshot:template,generateLink:false,pricing:{...form.pricing,total:form.pricing.totalOverridden?Number(form.pricing.total):total}},r=await fetch("/api/admin/contracts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),x=await safeJson(r);if(!r.ok)throw new Error([x.error,...(x.errors||[])].filter(Boolean).join(" "));if(!x.contract?.id)throw new Error("The draft was created, but its identifier was not returned.");router.push(`/admin/contracts/${x.contract.id}/edit`)}catch(e){setError(e.message||"The contract could not be duplicated.")}finally{setBusy(false)}};
  if(!template)return <p>{error||"Loading..."}</p>;
  const rep=template.sellerRepresentative||{};
  return <div className="space-y-7">
    <Panel title="1. Contract details" pages="Pages 1 & 3" description="The reference number and dates printed at the top of the Delivery Receipt and Order."><Fields form={form} set={set} fields={["orderNumber","orderDate","deliveryDate"]}/></Panel>
    <Panel title="2. Buyer and delivery" pages="Pages 1 & 3" description="Enter the buyer exactly as it should appear on the contract. Use the delivery field for the equipment destination."><Fields group="buyer" form={form} set={set} fields={["name","company","address","cityStateZip","phonePrimary","phoneSecondary","email","contact"]}/><div className="mt-5 border-t border-zinc-100 pt-5"><Fields form={form} set={set} fields={["deliveryAddress"]}/></div></Panel>
    <Panel title="3. Equipment" pages="Pages 1 & 3" description="These values fill the equipment description table in both the receipt and the order."><Fields group="equipment" form={form} set={set} fields={["make","model","year","serialNumber","hours","description"]}/></Panel>
    <Panel title="4. Pricing" pages="Page 3" description="Subtotal, taxes and shipping calculate the total automatically."><Fields group="pricing" form={form} set={set} fields={["subtotal","taxes","shipping"]}/><label className="mt-4 flex max-w-md items-start gap-3 rounded-xl border border-zinc-200 bg-zinc-50 p-3"><input type="checkbox" checked={form.pricing.totalOverridden} onChange={e=>set("pricing","totalOverridden",e.target.checked)} className="mt-1 h-4 w-4"/><span><b className="block text-sm">Enter a custom total</b><small className="text-zinc-500">Use only when the final total is different from subtotal + taxes + shipping.</small></span></label><input aria-label="Custom total" type="number" disabled={!form.pricing.totalOverridden} value={form.pricing.totalOverridden?form.pricing.total:total} onChange={e=>set("pricing","total",e.target.value)} className="admin-input mt-3 max-w-xs disabled:bg-zinc-100"/></Panel>
    <Panel title="5. Delivery checklist and warranties" pages="Page 1" description="Every selected item is printed as a checked box on the Delivery Receipt.">
      <Subheading title="Delivery checklist" hint="Select only the steps that were actually completed."/>
      <div className="grid gap-3 md:grid-cols-2">{DELIVERY_CHECKS.map(([key,label,hint])=><CheckCard key={key} checked={!!form.deliveryChecks[key]} onChange={checked=>set("deliveryChecks",key,checked)} label={label} hint={hint}/>)}</div>
      <div className="mt-7 border-t border-zinc-200 pt-6"><Subheading title="Warranties" hint="More than one option can be selected, matching the three boxes printed in the contract."/>
        <div className="grid gap-3 lg:grid-cols-3"><CheckCard checked={form.warranty.manufacturer} onChange={checked=>toggleWarranty("manufacturer",checked)} label="Manufacturer’s Warranty" hint="Select when the manufacturer warranty is still active."/><CheckCard checked={form.warranty.trial} onChange={checked=>toggleWarranty("trial",checked)} label="30-day trial" hint="Adds the 30-day inspection and rejection wording."/><CheckCard checked={form.warranty.other} onChange={checked=>toggleWarranty("other",checked)} label="Other warranty / terms" hint="Select for a seller warranty or another written condition."/></div>
        {form.warranty.manufacturer?<label className="mt-4 block max-w-sm"><span className="text-sm font-semibold">Manufacturer warranty expiration date</span><input type="date" lang="en-US" value={form.warranty.expiresAt||""} onChange={e=>set("warranty","expiresAt",e.target.value)} className="admin-input"/><small className="mt-1 block text-zinc-500">Printed on the line after “expires on” in US format{form.warranty.expiresAt?<>: <b>{formatWarrantyDate(form.warranty.expiresAt)}</b></>:" (example: August 21, 2026)"}.</small></label>:null}
        {form.warranty.other?<label className="mt-4 block"><span className="text-sm font-semibold">Other warranty explanation</span><textarea rows="3" value={form.warranty.text||""} onChange={e=>set("warranty","text",e.target.value)} placeholder="Example: The seller provides a comprehensive 12-month warranty." className="admin-input"/><small className="mt-1 block text-zinc-500">Printed after “Other (explain)” on page 1.</small></label>:null}
      </div>
    </Panel>
    <Panel title="6. Seller and signatures" pages="Pages 1, 2, 3 & 8" description="Seller details appear in the receipt/order. The representative signature appears twice in the paper contract."><Fields group="seller" form={form} set={set} fields={["name","legalName","address","cityStateZip","phone","email","representativeName"]}/><SellerSignaturePicker signatures={sellerSignatures} selectedUrl={rep.signatureUrl} onSelect={selectSellerSignature}/><div className="mt-6 grid gap-5 lg:grid-cols-2"><AssetPicker title="Upload a new seller signature" url={rep.signatureUrl} busy={uploading==="signature"} onFile={f=>uploadAsset(f,"signature")} transparent/><div className="space-y-4"><label className="block"><span className="text-sm font-semibold">Name printed below the seller signature</span><input value={rep.name||""} onChange={e=>setTemplate(t=>({...t,sellerRepresentative:{...t.sellerRepresentative,name:e.target.value}}))} className="admin-input"/></label><label className="block"><span className="text-sm font-semibold">Seller signature date</span><input type="date" value={rep.signedDate||""} onChange={e=>setTemplate(t=>({...t,sellerRepresentative:{...t.sellerRepresentative,signedDate:e.target.value}}))} className="admin-input"/><small className="mt-1 block text-zinc-500">Appears below the seller signature on pages 2 and 8.</small></label></div></div><div className="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="text-sm text-amber-950">Save the current company, contact, representative and signature as the starting values for every new contract.</p><button type="button" disabled={busy||!!uploading} onClick={saveSellerDefaults} className="mt-3 rounded-lg bg-[#c9a227] px-4 py-2 text-sm font-bold text-black transition hover:bg-[#b6921f] disabled:opacity-50">{busy?"Saving...":"Save seller details for future contracts"}</button></div></Panel>
    <Panel title="7. Advanced wording and branding" pages="All pages" description="Normally you can leave this section unchanged."><details className="group rounded-xl border border-zinc-200 bg-zinc-50"><summary className="cursor-pointer list-none p-4 font-bold">Show logo and legal wording <span className="float-right text-zinc-500 group-open:rotate-180">⌄</span></summary><div className="border-t border-zinc-200 p-4"><AssetPicker title="Contract logo" url={template.logoUrl} busy={uploading==="logo"} onFile={f=>uploadAsset(f,"logo")}/><label className="mt-5 block">Introduction<textarea rows="5" value={template.introduction||""} onChange={e=>setTemplate(t=>({...t,introduction:e.target.value}))} className="admin-input"/></label>{template.terms.map((term,i)=><div key={term.number||i} className="mt-4 rounded-xl border bg-white p-4"><div className="flex gap-3"><b>{i+1}.</b><input value={term.title} onChange={e=>setTemplate(t=>({...t,terms:t.terms.map((x,j)=>j===i?{...x,title:e.target.value}:x)}))} className="w-full border-b bg-transparent font-bold outline-none"/></div><textarea rows="7" value={term.body} onChange={e=>setTemplate(t=>({...t,terms:t.terms.map((x,j)=>j===i?{...x,body:e.target.value}:x)}))} className="admin-input mt-3"/></div>)}<button type="button" disabled={busy||!!uploading} onClick={saveBranding} className="mt-5 rounded-lg border-2 border-[#c9a227] px-4 py-2 font-semibold hover:bg-[#c9a227]/10">Save branding and wording for future contracts</button></div></details></Panel>
    {!id?<Panel title="8. Client link" description="Optional: set a deadline after which the client can no longer open or sign this link."><label><span className="text-sm font-semibold">Link expiration date and time</span><input type="datetime-local" value={form.linkExpiresAt||""} onChange={e=>set(null,"linkExpiresAt",e.target.value)} className="admin-input max-w-md"/></label></Panel>:null}
    <Panel title={`${id?"8":"9"}. Quick review`} description={id?"Check the key details before saving the changes or duplicating this contract as a draft.":"Check the key details before saving or creating the client link."}><div className="rounded-lg bg-zinc-50 p-4"><p className="font-serif text-lg font-bold">{form.buyer.name||"Buyer name not entered"}</p><p>{[form.equipment.year,form.equipment.make,form.equipment.model].filter(Boolean).join(" ")||"Equipment not entered"}</p><p className="mt-2 font-bold">Total: {total.toFixed(2)} {form.pricing.currency}</p><p className="mt-3 text-sm text-zinc-600">Delivery checks selected: {Object.values(form.deliveryChecks).filter(Boolean).length}/5 · Warranties selected: {[form.warranty.manufacturer,form.warranty.trial,form.warranty.other].filter(Boolean).length}/3</p></div></Panel>
    {error?<p role="alert" className="rounded-lg bg-red-50 p-4 text-red-700">{error}</p>:null}{notice?<p role="status" className="rounded-lg bg-amber-50 p-4 text-amber-900">{notice}</p>:null}
    {link?<div className="rounded-xl border-2 border-[#c9a227] bg-white p-4"><b>Copy this link now:</b><input readOnly value={link} className="admin-input mt-2"/><button type="button" onClick={()=>navigator.clipboard.writeText(link)} className="mt-2 rounded-lg bg-black px-4 py-2 text-white">Copy Link</button></div>:null}
    <div className="flex flex-wrap gap-3"><button type="button" disabled={busy||!!uploading} onClick={()=>save(false)} className="rounded-lg bg-zinc-700 px-5 py-3 text-white disabled:opacity-50">{id?"Save changes":"Save as draft"}</button>{!id?<button type="button" disabled={busy||!!uploading} onClick={()=>save(true)} className="rounded-lg bg-[#c9a227] px-5 py-3 font-bold disabled:opacity-50">Generate Link</button>:null}{id&&form.status==="draft"?<button type="button" disabled={busy||!!uploading} onClick={publish} className="rounded-lg bg-emerald-700 px-5 py-3 font-bold text-white transition hover:bg-emerald-800 disabled:opacity-50">Publish</button>:null}{id&&form.status!=="signed"?<button type="button" disabled={busy||!!uploading} onClick={duplicateAsDraft} className="rounded-lg bg-[#c9a227] px-5 py-3 font-bold text-black disabled:opacity-50">Duplicate as a draft</button>:null}</div>
  </div>
}

function AssetPicker({title,url,busy,onFile,transparent=false}){return <div className="rounded-xl border border-dashed border-zinc-400 p-4"><p className="font-semibold">{title}</p><div className={`mt-3 flex h-32 items-center justify-center rounded-lg border ${transparent?"bg-zinc-100":"bg-white"}`}>{url?<img src={url} alt={`${title} preview`} className="max-h-28 max-w-full object-contain"/>:<span className="text-sm text-zinc-500">No image selected</span>}</div><label className="mt-3 inline-flex cursor-pointer rounded-lg bg-black px-4 py-2 text-sm font-semibold text-white">{busy?"Uploading...":"Choose image"}<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>onFile(e.target.files?.[0])} className="sr-only"/></label><p className="mt-2 text-xs text-zinc-500">PNG, JPG or WEBP, maximum 3 MB. Transparent PNG is recommended.</p></div>}
function Panel({title,pages,description,children}){return <section className="rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm sm:p-6"><div className="mb-5 flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-bold">{title}</h2>{description?<p className="mt-1 max-w-3xl text-sm text-zinc-600">{description}</p>:null}</div>{pages?<span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-bold text-[#806515] ring-1 ring-amber-200">{pages}</span>:null}</div>{children}</section>}
function Subheading({title,hint}){return <div className="mb-3"><h3 className="font-bold text-zinc-900">{title}</h3><p className="text-sm text-zinc-500">{hint}</p></div>}
function CheckCard({checked,onChange,label,hint}){return <label className={`flex cursor-pointer items-start gap-3 rounded-xl border p-3 transition ${checked?"border-[#c9a227] bg-amber-50":"border-zinc-200 bg-white hover:border-zinc-400"}`}><input type="checkbox" checked={!!checked} onChange={e=>onChange(e.target.checked)} className="mt-1 h-5 w-5 shrink-0 accent-[#a98616]"/><span><b className="block text-sm text-zinc-900">{label}</b><small className="mt-0.5 block leading-5 text-zinc-500">{hint}</small></span></label>}
function SellerSignaturePicker({signatures,selectedUrl,onSelect}){return <div className="mt-6 border-t border-zinc-200 pt-5"><div className="flex flex-wrap items-end justify-between gap-2"><div><h3 className="font-bold">Choose a saved seller / employee signature</h3><p className="mt-1 text-sm text-zinc-500">The selected signature is stored with this contract and printed on pages 2 and 8 of the PDF.</p></div><span className="rounded-full bg-zinc-100 px-2.5 py-1 text-xs font-semibold">{signatures.length} available</span></div>{signatures.length?<div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{signatures.map(signature=>{const selected=signature.url===selectedUrl;return <button key={signature._id||signature.url} type="button" onClick={()=>onSelect(signature)} className={`overflow-hidden rounded-xl border-2 text-left transition ${selected?"border-[#c9a227] bg-amber-50 shadow-sm":"border-zinc-200 bg-white hover:border-zinc-400"}`}><span className="flex h-24 items-center justify-center bg-white p-3"><img src={signature.url} alt={`Signature of ${signature.name}`} className="max-h-20 max-w-full object-contain"/></span><span className="block border-t border-zinc-100 p-3"><b className="block text-sm">{signature.name}</b><small className={selected?"font-bold text-[#806515]":"text-zinc-500"}>{selected?"Selected for this contract":signature.isDefault?"Current default · select":"Select this signature"}</small></span></button>})}</div>:<p className="mt-3 rounded-lg bg-zinc-50 p-3 text-sm text-zinc-500">No saved seller signatures are available. Upload one below.</p>}</div>}
function Fields({group,form,set,fields}){return <div className="grid gap-4 sm:grid-cols-2">{fields.map(k=>{const path=group?`${group}.${k}`:k,meta=FIELD_META[path]||FIELD_META[k]||{},value=(group?form[group]?.[k]:form[k])??"",type=meta.type||(["subtotal","taxes","shipping"].includes(k)?"number":["orderDate","deliveryDate"].includes(k)?"date":"text");return <label key={k} className={["description","deliveryAddress"].includes(k)?"sm:col-span-2":""}><span className="mb-1 block text-sm font-semibold">{meta.label||human(k)}{REQUIRED_FIELDS.has(path)?<span className="ml-1 text-red-600">*</span>:null}</span><input type={type} required={REQUIRED_FIELDS.has(path)} placeholder={meta.placeholder||""} value={value} onChange={e=>set(group,k,e.target.value)} className="admin-input"/>{meta.hint?<small className="mt-1 block text-zinc-500">{meta.hint}</small>:null}</label>})}</div>}
const REQUIRED_FIELDS=new Set(["orderNumber","buyer.name","buyer.email","equipment.model"]);
const FIELD_META={orderNumber:{label:"Order / invoice number",placeholder:"Example: 394110",hint:"The same number is used on the Delivery Receipt and Order."},orderDate:{label:"Order date"},deliveryDate:{label:"Delivery date"},"buyer.name":{label:"Buyer full legal name"},company:{label:"Buyer company (optional)"},"buyer.address":{label:"Buyer street address"},cityStateZip:{label:"City, state and ZIP",placeholder:"Example: Pomeroy, OH 45769"},phonePrimary:{label:"Primary phone",type:"tel"},phoneSecondary:{label:"Secondary phone (optional)",type:"tel"},"buyer.email":{label:"Buyer email",type:"email"},contact:{label:"Contact person (if different)",hint:"Leave blank when the buyer is also the contact person."},deliveryAddress:{label:"Delivery location — full address",placeholder:"Street, city, state and ZIP",hint:"Leave blank only when it is the same as the buyer address."},make:{label:"Make",placeholder:"Example: Case IH"},model:{label:"Model",placeholder:"Example: Farmall 120C"},year:{label:"Year"},serialNumber:{label:"Serial number"},hours:{label:"Hours (if applicable)"},description:{label:"Description and notes",placeholder:"Adjustments, included attachments, condition notes, etc."},subtotal:{label:"Equipment subtotal (USD)"},taxes:{label:"Taxes (USD)"},shipping:{label:"Shipping and handling (USD)"},"seller.name":{label:"Seller display name"},legalName:{label:"Seller legal name"},"seller.address":{label:"Seller street address"},"seller.cityStateZip":{label:"Seller city, state and ZIP"},representativeName:{label:"Fallback representative name",hint:"Used only if no name is set with the seller signature."},phone:{label:"Seller phone",type:"tel"},"seller.email":{label:"Seller email",type:"email"}};
function normalizeWarranty(w={}){const type=String(w.type||"").toLowerCase(),hasExplicit=[w.manufacturer,w.trial,w.other].some(value=>typeof value==="boolean");return hasExplicit?w:{...w,manufacturer:type.includes("manufacturer"),trial:type.includes("30")||type.includes("trial"),other:Boolean(w.text)||(!type.includes("manufacturer")&&!type.includes("30")&&!type.includes("trial"))}}
function sellerDefaults(t={}){const c=t.company||{},r=t.sellerRepresentative||{};return{...blank.seller,name:c.name||blank.seller.name,legalName:c.legalName||blank.seller.legalName,address:c.address||blank.seller.address,cityStateZip:c.cityStateZip||blank.seller.cityStateZip,phone:c.phone||blank.seller.phone,email:c.email||blank.seller.email,representativeName:r.name||blank.seller.representativeName}}
function formatWarrantyDate(value){return value?new Intl.DateTimeFormat("en-US",{timeZone:"UTC",month:"long",day:"numeric",year:"numeric"}).format(new Date(value)):""}
function human(v){return v.replace(/([A-Z])/g," $1").replace(/^./,x=>x.toUpperCase())} function short(v){return v?new Date(v).toISOString().slice(0,10):""} function local(v){return v?new Date(v).toISOString().slice(0,16):""}
async function safeJson(response){const text=await response.text();if(!text)throw new Error(`Server returned an empty response (${response.status}).`);try{return JSON.parse(text)}catch{throw new Error(`Server returned an invalid response (${response.status}).`)}}
