import nodemailer from "nodemailer";

export const DEFAULT_CONTRACT_NOTIFICATION_RECIPIENTS=["sales@sandwequipments.com","sara.mara.diaz@proton.me"];

export function contractNotificationRecipients(){const configured=[process.env.CONTRACT_NOTIFICATION_EMAILS,process.env.CONTRACT_NOTIFICATION_EMAIL].filter(Boolean).join(",").split(/[,;\s]+/).map(value=>value.trim().toLowerCase()).filter(value=>/^\S+@\S+\.\S+$/.test(value));return[...new Set([...DEFAULT_CONTRACT_NOTIFICATION_RECIPIENTS,...configured])]}

export function buildSignedNotification(contract,{baseUrl=process.env.NEXT_PUBLIC_APP_URL?.replace(/\/$/,"")||""}={}){
  const id=String(contract._id||contract.id||"contract"),order=String(contract.orderNumber||"—"),buyer=contract.buyer||{},equipment=contract.equipment||{},pricing=contract.pricing||{},signedAt=contract.signedAt?new Date(contract.signedAt):new Date(),signedLabel=formatDate(signedAt),method=contract.signatureMethod==="typed_consent"?"Typed signature and electronic consent":"Drawn electronic signature",equipmentLabel=[equipment.year,equipment.make,equipment.model].filter(Boolean).join(" ")||"—",address=[buyer.address,buyer.cityStateZip].filter(Boolean).join(", ")||"—",adminUrl=`${baseUrl}/admin/contracts/${id}/signed`,pdfUrl=`${baseUrl}/api/admin/contracts/${id}/pdf?version=signed`,messageId=`<contract-${safeId(id)}-${signedAt.getTime()}@sandwequipments.com>`,subject=`Signed contract #${order} — ${buyer.name||contract.signerName||"Customer"}`;
  const rows=[
    ["Customer",buyer.name||"—"],["Company",buyer.company||"—"],["Email",buyer.email||"—"],["Phone",buyer.phonePrimary||"—"],["Address",address],
    ["Equipment",equipmentLabel],["Serial number",equipment.serialNumber||"—"],["Hours",equipment.hours||"—"],["Contract total",formatMoney(pricing.total,pricing.currency)],
    ["Signed by",contract.signerName||buyer.name||"—"],["Signing method",method],["Signed at",signedLabel],["IP address",contract.auditIp||"Unavailable"],["Browser / device",contract.auditUserAgent||"Unavailable"],
  ];
  const text=[`Contract #${order} was signed.`,"",...rows.map(([label,value])=>`${label}: ${value}`),"",`View signed contract: ${adminUrl}`,`Download signed PDF: ${pdfUrl}`,"",`Notification ID: ${messageId}`].join("\n");
  const rowHtml=rows.map(([label,value])=>`<tr><td style="padding:9px 12px;color:#71717a;font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:.04em;border-bottom:1px solid #eee;vertical-align:top;width:34%">${escapeHtml(label)}</td><td style="padding:9px 12px;color:#18181b;font-size:14px;border-bottom:1px solid #eee;vertical-align:top">${escapeHtml(value)}</td></tr>`).join("");
  const html=`<!doctype html><html><body style="margin:0;padding:0;background:#f4f4f2;font-family:Arial,Helvetica,sans-serif;color:#18181b"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f4f4f2"><tr><td align="center" style="padding:28px 12px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:680px;background:#fff;border:1px solid #e4e4e7;border-radius:14px;overflow:hidden"><tr><td style="background:#111;padding:24px 28px;border-bottom:4px solid #c9a227"><div style="color:#c9a227;font-size:12px;font-weight:700;letter-spacing:.14em;text-transform:uppercase">S &amp; W Equipment</div><h1 style="margin:8px 0 0;color:#fff;font-size:25px;line-height:1.25">Contract signed successfully</h1></td></tr><tr><td style="padding:24px 28px"><p style="margin:0 0 6px;font-size:16px">Contract <strong>#${escapeHtml(order)}</strong> was signed by <strong>${escapeHtml(contract.signerName||buyer.name||"Customer")}</strong>.</p><p style="margin:0 0 22px;color:#52525b;font-size:14px">The agreement is now read-only. The details captured at signing are below.</p><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border:1px solid #e4e4e7;border-radius:10px;border-collapse:separate;border-spacing:0;overflow:hidden">${rowHtml}</table><table role="presentation" cellspacing="0" cellpadding="0" style="margin-top:24px"><tr><td style="padding-right:10px;padding-bottom:10px"><a href="${escapeHtml(adminUrl)}" style="display:inline-block;background:#111;color:#fff;text-decoration:none;font-size:14px;font-weight:700;padding:12px 18px;border-radius:8px">View signed contract</a></td><td style="padding-bottom:10px"><a href="${escapeHtml(pdfUrl)}" style="display:inline-block;background:#c9a227;color:#111;text-decoration:none;font-size:14px;font-weight:700;padding:12px 18px;border-radius:8px">Download signed PDF</a></td></tr></table><p style="margin:14px 0 0;color:#71717a;font-size:12px;line-height:1.5">This automatic notification was sent once for this signing event. Keep the contract number when contacting the customer.</p></td></tr></table></td></tr></table></body></html>`;
  return{subject,text,html,messageId,adminUrl,pdfUrl};
}

export async function sendSignedNotification(contract){
  const host=process.env.SMTP_HOST,user=process.env.SMTP_USER,pass=process.env.SMTP_PASS,from=process.env.MAIL_FROM||user;if(!host||!user||!pass||!from)throw new Error("SMTP notification settings are incomplete.");
  const transporter=nodemailer.createTransport({host,port:Number(process.env.SMTP_PORT||587),secure:Number(process.env.SMTP_PORT)===465,auth:{user,pass}}),recipients=contractNotificationRecipients(),message=buildSignedNotification(contract);
  const result=await transporter.sendMail({from,to:recipients,replyTo:contract.buyer?.email||undefined,subject:message.subject,text:message.text,html:message.html,messageId:message.messageId,headers:{"X-Contract-ID":String(contract._id||contract.id||"")}});
  return{messageId:result.messageId||message.messageId,recipients};
}

function escapeHtml(value){return String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[char])}
function safeId(value){return String(value).replace(/[^A-Za-z0-9.-]/g,"-").slice(0,100)}
function formatDate(value){return new Intl.DateTimeFormat("en-US",{timeZone:"America/Chicago",dateStyle:"long",timeStyle:"long"}).format(value)}
function formatMoney(value,currency="USD"){return new Intl.NumberFormat("en-US",{style:"currency",currency:currency||"USD"}).format(Number(value||0))}
