import fs from "node:fs";
import path from "node:path";
import { signatureMethod } from "./security.js";
import { contractCompany } from "./company.js";
import { contractEquipmentItems, equipmentPrice } from "./equipment.js";
import { plainTextToRichHtml, richTextBlocks } from "./richText.js";

const W=612,H=792,M=36,REFUND="Right to Refund: The Client shall be entitled to a full refund of the initial purchase price provided that a written request for cancellation is submitted within 30 calendar days of the effective date. Refunds will be processed via the original payment method within [3] business days of approval.";

export function generateContractPdf(c,{signed=false,includeSeller=true,sellerSignature=null,logo=null}={}){
  const contract={...c,_pdfLogo:logo},t=contract.templateSnapshot||{},terms=t.terms||[],p1=splitAt(terms[0]?.body,"in this Agreement."),p8=splitAt(terms[7]?.body,"expenses, demands,"),p10=paras(terms[9]?.body),p11=splitAt(terms[10]?.body,"For further information,"),p14=paras(terms[13]?.body),opt={signed,includeSeller,sellerSignature},multiple=contractEquipmentItems(contract).length>1;
  const streams=multiple
    ?[pageOne(contract,t,true),pageTwo(contract,t,opt,true),pageThree(contract,t,null,"",true),termsOpeningPage(contract,t,terms),legalPage([...terms.slice(5,9),{...terms[9],body:p10.slice(0,4).join("\n\n")}],5),multiPageSix(contract,p10.slice(4),terms[10],terms[10]?.body,terms[11]),multiPageSeven(terms[12],terms[13],p14),multiFinalPage(contract,t,opt)]
    :[pageOne(contract,t,false),pageTwo(contract,t,opt,false),pageThree(contract,t,terms[0],p1[0],false),legalPage([p1[1],...terms.slice(1,7),{...terms[7],body:p8[0]}],4),legalPage([p8[1],...terms.slice(8,10),{...terms[10],body:p11[0]}],5),pageSix(contract,p11[1],terms[11],terms[12],terms[13],p14.slice(0,2),6),pageSeven(t,p14.slice(2),7),pageEight(contract,t,opt,8)];
  return buildPdf(streams,sellerSignature,logo);
}

function pageOne(c,t,multiple){const d=new Painter();header(d,c,t);d.title("DELIVERY RECEIPT");partyTable(d,c,true);equipment(d,c);d.y+=multiple?7:13;checks(d,c);if(!multiple){d.y+=27;warrantySection(d,c,t)}footer(d,1);return d.finish()}
function pageTwo(c,t,opt,multiple){const d=new Painter();if(multiple){d.y=57;warrantySection(d,c,t);d.y+=10}else d.y=48;d.center("BUYER DECLARATIONS",12,true);d.y+=34;declarations(d,t);signatures(d,c,t,opt,multiple?d.y+24:218);footer(d,2);return d.finish()}
function pageThree(c,t,term,body,multiple){const count=contractEquipmentItems(c).length,d=new Painter(count===3?854:H);header(d,c,t);d.title("ORDER");partyTable(d,c,false);if(multiple){d.y+=7;d.text("DESCRIPTION:",M,d.y+10,11,true);d.y+=12}else{d.y+=15;d.text("DESCRIPTION:",M,d.y+15,11,true);d.y+=4}equipment(d,c);prices(d,c);if(!multiple){d.y+=41;termsOpening(d,c,t,term,body)}footer(d,3);return d.finish()}
function termsOpeningPage(c,t,terms){const d=new Painter();d.y=42;termsOpening(d,c,t,terms[0],terms[0]?.body);for(const term of terms.slice(1,5)){d.y+=2.5;drawTerm(d,term)}footer(d,4);return d.finish()}
function termsOpening(d,c,t,term,body){d.center("TERMS & CONDITIONS",12,true,true);d.y+=37;agreementDate(d,c);d.y+=7;for(const x of paras(t.introduction)){d.paragraph(x,{size:10.5,leading:13,justify:true});d.y+=7}drawTerm(d,{...term,body})}
function warrantySection(d,c,t){d.center("WARRANTIES",12,true);d.y+=8;warranties(d,c);d.y+=24;d.paragraph(t.warrantyDisclaimer||"",{x:49,width:514,bold:true,size:12,leading:13,justify:true});d.y+=18;d.paragraph(REFUND,{x:49,width:514,bold:true,size:12,leading:13,justify:true})}
function declarations(d,t){for(const x of t.buyerDeclarations||[]){d.dot(56,d.y-4,2.2);d.paragraph(x,{x:72,width:500,size:12,leading:14.5});d.y+=2}}
function multiPageSix(c,remainingTerm10,term11,body11,term12){const d=new Painter();d.y=28;drawSubs(d,remainingTerm10,11,12.8);d.y+=7;drawTerm(d,{...term11,body:body11});d.y+=7;drawTerm(d,term12);d.y+=18;notice(d,c);footer(d,6);return d.finish()}
function multiPageSeven(term13,term14,firstTerm14){const d=new Painter();d.y=28;drawTerm(d,term13);d.y+=4;drawTerm(d,{...term14,body:firstTerm14.join("\n\n")});footer(d,7);return d.finish()}
function multiFinalPage(c,t,opt){const d=new Painter();d.y=28;d.paragraph(t.confirmationText||"",{bold:true,size:11,leading:12.8,justify:true});d.y+=22;leadParagraph(d,"IN WITNESS WHEREOF,",String(t.witnessText||"").replace(/^IN WITNESS WHEREOF,\s*/,""),{size:10.5,leading:12,justify:true});signatures(d,c,t,opt,Math.max(d.y+34,207));footer(d,8);return d.finish()}
function legalPage(items,n){const d=new Painter();d.y=28;for(const item of items){if(!item)continue;if(typeof item==="string")d.paragraph(item,{x:54,width:522,size:11,leading:12.8,justify:true});else drawTerm(d,item);d.y+=2.5}footer(d,n);return d.finish()}
function pageSix(c,cont,t12,t13,t14,p14,n){const d=new Painter();d.y=38;d.paragraph(cont,{x:90,width:486,size:11,leading:12.8,justify:true});d.y+=8;drawTerm(d,t12);d.y+=22;notice(d,c);d.y+=18;drawTerm(d,t13);d.y+=4;drawTerm(d,{...t14,body:p14.join("\n\n")});footer(d,n);return d.finish()}
function pageSeven(t,items,n){const d=new Painter();d.y=28;drawSubs(d,items,11,12.8);d.y+=8;d.paragraph(t.confirmationText||"",{bold:true,size:11,leading:12.8,justify:true});footer(d,n);return d.finish()}
function pageEight(c,t,opt,n){const d=new Painter();d.y=48;leadParagraph(d,"IN WITNESS WHEREOF,",String(t.witnessText||"").replace(/^IN WITNESS WHEREOF,\s*/,""),{size:10.5,leading:12,justify:true});signatures(d,c,t,opt,172);footer(d,n);return d.finish()}

function header(d,c,t){const x=contractCompany(c),legal=String(x.legalName||x.name||"Seller company"),left=407,right=576,source=c._pdfLogo||{width:532,height:300},fitted=containImage(source.width||532,source.height||300,157,74);d.image(36+(157-fitted.width)/2,28+(74-fitted.height)/2,fitted.width,fitted.height);[[x.name,30],[x.address,42],[x.cityStateZip,54],[x.phone,66],[x.email,78],[x.website,90]].forEach(([s,y])=>centeredFit(d,s,left,right,y,9.5,true));d.line(424,96,576,96,.4);centeredFit(d,`${x.name||"Seller company"} is a registered`,left,right,103,7,true);centeredFit(d,`trade name of "${legal}"`,left,right,113,7,true);d.y=161}
function centeredFit(d,value,left,right,y,size,bold){const text=String(value||"");let fitted=size;while(fitted>6.5&&textWidth(text,fitted,bold)>right-left)fitted-=.25;d.text(text,left+(right-left-textWidth(text,fitted,bold))/2,y,fitted,bold)}
function partyTable(d,c,delivery){const top=d.y,rows=delivery?[32,52,51]:[32,76,55],split=276,leftWidth=split-M,rightWidth=W-M-split,sellerValue=delivery?[c.seller?.legalName||c.seller?.name,c.seller?.phone,c.seller?.email].filter(Boolean).join("\n"):seller(c.seller);d.line(M,top,W-M,top,.45);let y=top;for(const h of rows){y+=h;d.line(M,y,W-M,y,.45)}cell(d,M,top,`${delivery?"Invoice":"Order"} #:`,c.orderNumber,rows[0],leftWidth);cell(d,split,top,`${delivery?"Delivery":"Order"} Date:`,shortDate(delivery?c.deliveryDate:c.orderDate),rows[0],rightWidth);cell(d,M,top+rows[0],"Buyer:",buyer(c.buyer),rows[1],leftWidth);cell(d,split,top+rows[0],"Seller:",sellerValue,rows[1],rightWidth);cell(d,M,top+rows[0]+rows[1],"Contact:",[c.buyer?.contact||c.buyer?.name,c.buyer?.phonePrimary,c.buyer?.phoneSecondary].filter(Boolean).join("\n"),rows[2],leftWidth);cell(d,split,top+rows[0]+rows[1],"Delivery Location:",address(c),rows[2],rightWidth);d.y=y}
function cell(d,x,y,label,value,height=32,width=240){d.text(label,x+5,y+Math.min(11,height*.42),11,true);let size=11,leading=12,lines=cellLines(value,width-10,size);while(size>8&&24+Math.max(0,lines.length-1)*leading>height-4){size-=.5;leading=size+1;lines=cellLines(value,width-10,size)}const valueY=Math.min(24,height-5-Math.max(0,lines.length-1)*leading);lines.forEach((s,i)=>d.text(s,x+5,y+valueY+i*leading,size,false,"F3"))}
function cellLines(value,width,size){return String(value||"").split("\n").flatMap(line=>wrapToWidth(line,width,size))}
function equipment(d,c){const items=contractEquipmentItems(c);for(const [index,item] of items.entries()){if(items.length>1){d.y+=9;d.text(`EQUIPMENT ${index+1}`,M,d.y,8,true);d.y+=1}equipmentTable(d,item,c,items.length)}}
function equipmentTable(d,item,c,count){const multi=count>1,top=d.y+(multi?8:14),x=[M,225,391,W-M],a=multi?27:25,e=27,widths=x.slice(0,-1).map((v,i)=>x[i+1]-v),richWidth=W-M*2-10,html=item.descriptionHtml||plainTextToRichHtml(item.description||""),preferred=multi?8:9,contentHeight=richTextHeight(html,richWidth,preferred),b=Math.max(multi?48:52,Math.min(multi?72:90,Math.ceil(contentHeight+24)));d.rect(M,top,W-M*2,a+b+e);d.line(M,top+a,W-M,top+a);d.line(M,top+a+b,W-M,top+a+b);for(const xx of x.slice(1,-1)){d.line(xx,top,xx,top+a);d.line(xx,top+a+b,xx,top+a+b+e)}cell(d,x[0],top,"Model:",item.model,a,widths[0]);cell(d,x[1],top,"Year:",item.year,a,widths[1]);cell(d,x[2],top,"Serial No:",item.serialNumber,a,widths[2]);richCell(d,M,top+a,"Description & Notes:",html,b,W-M*2,preferred);cell(d,x[0],top+a+b,"Make:",item.make,e,widths[0]);cell(d,x[1],top+a+b,"Hours (if applicable):",item.hours,e,widths[1]);const price=equipmentPrice(item,c,count),priceValue=price===null?"Included in subtotal":money(price,c.pricing?.currency);cell(d,x[2],top+a+b,"Price:",priceValue,e,widths[2]);d.y=top+a+b+e}
function richCell(d,x,y,label,html,height,width,size){const availableHeight=height-24,fitted=fitRichTextSize(html,width-10,availableHeight,size);d.text(label,x+5,y+11,Math.min(11,fitted+2),true);d.richText(html,{x:x+5,y:y+22,width:width-10,height:availableHeight,size:fitted})}
function checks(d,c){const a=c.deliveryChecks||{},l=[[a.deliveryCompleted,"Delivery completed"],[a.buyerInspected,"Delivery inspection completed by Buyer"],[a.manualsGiven,"Applicable Owner's and Safety Manuals given"]],r=[[a.safetyExplained,"Use and safety procedures explained"],[a.maintenanceExplained,"Maintenance procedures explained"]];l.forEach((x,i)=>check(d,37,d.y+i*13,...x));r.forEach((x,i)=>check(d,325,d.y+i*13,...x));d.y+=39}
function check(d,x,y,on,label){d.rect(x,y,12,12);if(on)d.checkmark(x,y);d.text(label,x+15,y+10,12)}
function warranties(d,c){const w=c.warranty||{},selected=warrantySelections(w),manufacturer="The equipment is covered under a Manufacturer's Warranty, which expires on",lineStart=Math.min(448,52+textWidth(manufacturer,12)+5),lineEnd=576;check(d,37,d.y,selected.manufacturer,manufacturer);d.line(lineStart,d.y+11,lineEnd,d.y+11,.45);d.centerAt(warrantyDate(w.expiresAt),lineStart,lineEnd,d.y+8,10);d.y+=14;check(d,37,d.y,selected.trial,"A 30-day trial begins upon delivery. If the Buyer does not reject the equipment by phone or in writing");d.y+=25;d.text("within 30 days, the sale becomes final and 'as-is' with no further seller liability.",50,d.y,10.5);d.y+=20;check(d,37,d.y,selected.other,`Other (explain): ${w.text||""}`);d.y+=14}
function prices(d,c){const multiple=contractEquipmentItems(c).length>1;d.y+=multiple?13:14;[["SUBTOTAL",c.pricing?.subtotal],["TAXES",c.pricing?.taxes],["SHIPPING AND HANDLING",c.pricing?.shipping],[`TOTAL PRICE (${c.pricing?.currency||"USD"})`,c.pricing?.total]].forEach(([k,v])=>{d.text(`${k}:`,multiple?351.5:363,d.y,10.5,true);d.text(money(v,c.pricing?.currency),multiple?515:520,d.y,10.5);d.y+=multiple?13.4:13})}
function drawTerm(d,t){if(!t)return;const ps=paras(t.body),bold=[6,7].includes(Number(t.number)),startsWithSub=/^[a-i]\.\s/.test(ps[0]||"");d.text(`${t.number}.`,M,d.y,11);d.text(`${t.title}.`,54,d.y,11);const tw=Math.min(220,textWidth(`${t.title}.`,11));d.line(54,d.y+2,54+tw,d.y+2,.4);if(startsWithSub){d.y+=15;drawSubs(d,ps,11,12.8);return}const x=68+tw;d.flowParagraph(ps[0]||"",{firstX:x,firstWidth:W-M-x,nextX:54,nextWidth:W-M-54,size:11,leading:12.8,firstY:d.y,bold,justify:true});d.y+=4;if(ps.length>1)drawSubs(d,ps.slice(1),11,12.8)}
function drawSubs(d,items,size,leading){for(const [i,s] of items.entries()){const m=s.match(/^([a-i])\.\s*(.*)$/s),text=m?.[2]||s,[heading,rest]=subheading(text);d.text(`${m?.[1]||String.fromCharCode(97+i)}.`,72,d.y,size);if(heading){d.text(heading,90,d.y,size);const hw=textWidth(heading,size);d.line(90,d.y+2,90+hw,d.y+2,.4);d.flowParagraph(rest,{firstX:94+hw,firstWidth:W-M-(94+hw),nextX:90,nextWidth:486,size,leading,firstY:d.y,justify:true})}else d.paragraph(text,{x:90,width:486,size,leading,justify:true});d.y+=4}}
function agreementDate(d,c){const y=d.y,lead="This Agreement is entered into as of",date=longDate(c.orderDate).split(" "),monthDay=date.slice(0,2).join(" "),year=date[2]||"",leadWidth=textWidth(lead,10.5),dateX=M+leadWidth+4,monthEnd=dateX+92,yearX=monthEnd+5,yearEnd=yearX+45,restX=yearEnd+6;d.text(lead,M,y,10.5);d.line(dateX,y+2,monthEnd,y+2,.45);d.centerAt(monthDay,dateX,monthEnd,y-1,10.5);d.line(yearX,y+2,yearEnd,y+2,.45);d.centerAt(year,yearX,yearEnd,y-1,10.5);d.flowParagraph('by and between Buyer and Seller, which jointly may be referred to as the "Parties."',{firstX:restX,firstWidth:W-M-restX,nextX:M,nextWidth:W-M*2,size:10.5,leading:13,firstY:y,justify:true})}
function leadParagraph(d,lead,rest,{x=M,width=W-M*2,size=10,leading=12,justify=false}={}){const lw=textWidth(lead,size,true),gap=8;d.text(lead,x,d.y,size,true);d.flowParagraph(rest,{firstX:x+lw+gap,firstWidth:width-lw-gap,nextX:x,nextWidth:width,size,leading,firstY:d.y,justify})}
function notice(d,c){const s=c.seller||{};d.text("If to Buyer:",40,d.y,10);d.text("If to Seller:",280,d.y,10);const a=buyer(c.buyer).split("\n"),b=[s.legalName||s.name,s.address,s.cityStateZip,s.phone,s.email].filter(Boolean);a.forEach((x,i)=>d.text(x,40,d.y+23+i*14,10));b.forEach((x,i)=>d.text(x,280,d.y+23+i*14,10));d.y+=23+Math.max(a.length,b.length)*14}
function signatures(d,c,t,{signed,includeSeller,sellerSignature},top){const l=41,r=351,w=210,rep=t.sellerRepresentative||{},name=rep.name||c.seller?.representativeName||"Seller Representative",hasOriginal=/daniel\s+r\.?\s+petrov/i.test(name)||rep.signatureUrl==="/contract-seller-signature.png",hasImage=Boolean(sellerSignature?.data)||hasOriginal;d.line(306,top-8,306,top+226);d.line(l,top+50,l+w,top+50);d.line(r,top+50,r+w,top+50);if(signed){if(signatureMethod(c)==="drawn"&&c.signature?.length)d.drawSignature(c.signature,l+10,top,w-20,43);else d.text(c.signerName||"",l+46,top+38,13,false,"F4")}if(includeSeller){if(hasImage){const fitted=containImage(sellerSignature?.width||320,sellerSignature?.height||68,165,43);d.signatureImage(r+29+(165-fitted.width)/2,top+(43-fitted.height)/2,fitted.width,fitted.height)}else d.text(name,r+45,top+38,13,false,"F4")}d.text("Buyer Representative Signature",l,top+64,10);d.text(`Signature - ${name}`,r+76,top+64,10);d.text(c.seller?.name||t.company?.name||"",r+120,top+78,10);d.line(l,top+131,l+w,top+131);d.line(r,top+131,r+w,top+131);d.centerAt(signed?c.signerName:c.buyer?.name,l,l+w,top+128,10);d.centerAt(name,r,r+w,top+128,10);d.text("Buyer Representative Printed Name",l,top+155,10);d.text("Seller Representative Printed Name",r,top+155,10);d.line(l,top+201,l+w,top+201);d.line(r,top+201,r+w,top+201);d.centerAt(signed?shortDate(c.signedAt):"",l,l+w,top+198,10);d.centerAt(rep.signedDate?sellerDate(rep.signedDate):"",r,r+w,top+198,10);d.text("Date",l,top+226,10);d.text("Date",r,top+226,10)}
function containImage(width,height,maxWidth,maxHeight){const scale=Math.min(maxWidth/width,maxHeight/height);return{width:width*scale,height:height*scale}}
function footer(d,n){d.center(String(n),10,false,false,d.height-18)}

class Painter{constructor(height=H){this.height=height;this.y=M;this.out="q 0 g 0 G"}finish(){return{stream:this.out,height:this.height}}text(s,x,y,size=10,bold=false,font="",wordSpacing=0){if(!s)return;this.out+=` BT /${font||(bold?"F2":"F1")} ${size} Tf ${wordSpacing?`${wordSpacing.toFixed(3)} Tw `:""}1 0 0 1 ${x} ${this.height-y} Tm (${esc(s)}) Tj ET`}center(s,size=10,bold=false,underline=false,y=this.y){const x=(W-s.length*size*.48)/2;this.text(s,x,y,size,bold);if(underline)this.line(x,y+2,W-x,y+2,.4)}centerAt(s,a,b,y,size){s=String(s||"");this.text(s,(a+b-s.length*size*.45)/2,y,size)}line(x1,y1,x2,y2,w=.5){this.out+=` ${w} w ${x1} ${this.height-y1} m ${x2} ${this.height-y2} l S`}rect(x,y,w,h){this.out+=` .5 w ${x} ${this.height-y-h} ${w} ${h} re S`}dot(x,y,r=2){const cy=this.height-y,k=r*.5522848;this.out+=` ${x+r} ${cy} m ${x+r} ${cy+k} ${x+k} ${cy+r} ${x} ${cy+r} c ${x-k} ${cy+r} ${x-r} ${cy+k} ${x-r} ${cy} c ${x-r} ${cy-k} ${x-k} ${cy-r} ${x} ${cy-r} c ${x+k} ${cy-r} ${x+r} ${cy-k} ${x+r} ${cy} c f`}checkmark(x,y){this.line(x+2,y+7,x+5,y+10,1.35);this.line(x+5,y+10,x+11,y+1,1.35)}image(x,y,w,h){this.out+=` q ${w} 0 0 ${h} ${x} ${this.height-y-h} cm /Im1 Do Q`}signatureImage(x,y,w,h){this.out+=` q ${w} 0 0 ${h} ${x} ${this.height-y-h} cm /Im2 Do Q`}paragraph(s,{x=M,width=W-M*2,size=10,leading=12,bold=false,firstY,justify=false}={}){const lines=wrapToWidth(s,width,size,bold);let y=firstY??this.y;for(const [i,line] of lines.entries()){this.text(line,x,y,size,bold,"",justify&&i<lines.length-1?wordSpace(line,width,size,bold):0);y+=leading}this.y=y}flowParagraph(s,{firstX,firstWidth,nextX,nextWidth,size,leading,firstY,bold=false,justify=false}){const words=String(s||"").replace(/\s+/g," ").trim().split(" ");let first="",used=0;while(used<words.length&&textWidth((first+" "+words[used]).trim(),size,bold)<=firstWidth){first=(first+" "+words[used++]).trim()}const segments=[];if(first)segments.push({line:first,x:firstX,width:firstWidth});for(const line of wrapToWidth(words.slice(used).join(" "),nextWidth,size,bold))segments.push({line,x:nextX,width:nextWidth});let y=firstY??this.y;for(const [i,segment] of segments.entries()){this.text(segment.line,segment.x,y,size,bold,"",justify&&i<segments.length-1?wordSpace(segment.line,segment.width,size,bold):0);y+=leading}this.y=y}richText(html,options){drawRichText(this,html,options)}title(s){this.center(s,16,true);this.line(M,this.y+5,W-M,this.y+5,.4);this.y+=5}drawSignature(strokes,x,y,w,h){this.out+=" q 1 w";for(const stroke of strokes){if(stroke.length<2)continue;stroke.forEach(([px,py],i)=>{this.out+=` ${x+px*w} ${this.height-(y+py*h)} ${i?"l":"m"}`});this.out+=" S"}this.out+=" Q"}}

function drawRichText(d,html,{x,y,width,height,size=9}){const maxY=y+height,blocks=richTextBlocks(html);for(const block of blocks){const lines=richBlockLines(block,width,size);for(const line of lines){if(y+line.leading>maxY)return;const lineWidth=line.runs.reduce((sum,run)=>sum+richRunWidth(run),0),start=block.align==="center"?x+(width-lineWidth)/2:block.align==="right"?x+width-lineWidth:x;let cursor=Math.max(x,start);for(const run of line.runs){const font=run.bold&&run.italic?"F6":run.italic?"F5":run.bold?"F2":"F1";d.text(run.text,cursor,y+run.size,run.size,run.bold,font);const runWidth=richRunWidth(run);if(run.underline)d.line(cursor,y+run.size+1,cursor+runWidth,y+run.size+1,.35);cursor+=runWidth}y+=line.leading}y+=Math.min(2,size*.2)}}
function richRunWidth(run){return /^\s+$/.test(run.text)?run.size*.32:textWidth(run.text,run.size,run.bold)*1.08}
function fitRichTextSize(html,width,height,preferred){let size=preferred;while(size>5.5&&richTextHeight(html,width,size)>height)size-=.5;return size}
function richTextHeight(html,width,size){return richTextBlocks(html).reduce((height,block)=>height+richBlockLines(block,width,size).reduce((sum,line)=>sum+line.leading,0)+Math.min(2,size*.2),0)}
function richBlockLines(block,width,baseSize){const headingScale={h1:1.55,h2:1.32,h3:1.16},blockScale=headingScale[block.type]||1,lines=[],prefix=block.type==="li"?(block.list==="ol"?`${block.listIndex}. `:"• "):"";let current=[],used=0,leading=baseSize*1.22;const flush=()=>{if(current.length)lines.push({runs:current,leading});current=[];used=0;leading=baseSize*1.22};if(prefix){const run={text:prefix,bold:false,italic:false,underline:false,size:baseSize};current.push(run);used=textWidth(prefix,baseSize)}for(const source of block.runs){const runSize=Math.max(5.5,baseSize*blockScale*fontSizeScale(source.size));for(const part of source.text.split(/(\n|\s+)/)){if(!part)continue;if(part==="\n"){flush();continue}const text=/^\s+$/.test(part)?" ":part,run={...source,text,size:runSize},runWidth=textWidth(text,runSize,run.bold);if(used&&text!==" "&&used+runWidth>width)flush();if(text===" "&&!current.length)continue;current.push(run);used+=runWidth;leading=Math.max(leading,runSize*1.2)}}flush();return lines}
function fontSizeScale(size){return({1:.72,2:.84,3:1,4:1.15,5:1.32,6:1.5,7:1.68})[size]||1}

function buildPdf(streams,sellerSignature,providedLogo){let logo,signature;try{logo=providedLogo?.data||fs.readFileSync(path.join(process.cwd(),"public","contract-logo.jpg"))}catch{logo=Buffer.alloc(0)}try{signature=sellerSignature?.data||fs.readFileSync(path.join(process.cwd(),"public","contract-seller-signature.jpg"))}catch{signature=Buffer.alloc(0)}const pages=streams.map(page=>typeof page==="string"?{stream:page,height:H}:page),logoSize=providedLogo||jpegDimensions(logo)||{width:532,height:300},signatureSize=sellerSignature||jpegDimensions(signature)||{width:320,height:68},pageStart=9,pageCount=pages.length,imageId=pageStart+pageCount*2,signatureId=imageId+1,objs=[null,"<< /Type /Catalog /Pages 2 0 R >>",`<< /Type /Pages /Kids [${pages.map((_,i)=>`${pageStart+i*2} 0 R`).join(" ")}] /Count ${pageCount} >>`,`<< /Type /Font /Subtype /Type1 /BaseFont /Times-Roman >>`,`<< /Type /Font /Subtype /Type1 /BaseFont /Times-Bold >>`,`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`,`<< /Type /Font /Subtype /Type1 /BaseFont /ZapfChancery-MediumItalic >>`,`<< /Type /Font /Subtype /Type1 /BaseFont /Times-Italic >>`,`<< /Type /Font /Subtype /Type1 /BaseFont /Times-BoldItalic >>`];for(let i=0;i<pageCount;i++){const p=pageStart+i*2,s=p+1,page=pages[i];objs[p]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${W} ${page.height}] /Resources << /Font << /F1 3 0 R /F2 4 0 R /F3 5 0 R /F4 6 0 R /F5 7 0 R /F6 8 0 R >> /XObject << /Im1 ${imageId} 0 R /Im2 ${signatureId} 0 R >> >> /Contents ${s} 0 R >>`;objs[s]=streamObject(Buffer.from(page.stream+" Q","binary"))}objs[imageId]=logo.length?imageObject(logo,logoSize.width,logoSize.height):streamObject(Buffer.from(""));objs[signatureId]=signature.length?imageObject(signature,signatureSize.width,signatureSize.height):streamObject(Buffer.from(""));return serialize(objs)}
function jpegDimensions(buffer){for(let offset=2;buffer?.length>offset+9;){if(buffer[offset]!==0xff){offset++;continue}const marker=buffer[offset+1],length=buffer.readUInt16BE(offset+2);if([0xc0,0xc1,0xc2,0xc3,0xc5,0xc6,0xc7,0xc9,0xca,0xcb,0xcd,0xce,0xcf].includes(marker))return{height:buffer.readUInt16BE(offset+5),width:buffer.readUInt16BE(offset+7)};if(!length)break;offset+=2+length}return null}
function streamObject(b){return Buffer.concat([Buffer.from(`<< /Length ${b.length} >>\nstream\n`,`binary`),b,Buffer.from("\nendstream","binary")])}function imageObject(b,width,height){return Buffer.concat([Buffer.from(`<< /Type /XObject /Subtype /Image /Width ${width} /Height ${height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${b.length} >>\nstream\n`,`binary`),b,Buffer.from("\nendstream","binary")])}
function serialize(objs){const parts=[Buffer.from("%PDF-1.4\n%âãÏÓ\n","binary")],offs=[0];let len=parts[0].length;for(let i=1;i<objs.length;i++){offs[i]=len;const body=Buffer.isBuffer(objs[i])?objs[i]:Buffer.from(objs[i],"binary"),part=Buffer.concat([Buffer.from(`${i} 0 obj\n`,`binary`),body,Buffer.from("\nendobj\n","binary")]);parts.push(part);len+=part.length}const xref=len;let tail=`xref\n0 ${objs.length}\n0000000000 65535 f \n`;for(let i=1;i<objs.length;i++)tail+=`${String(offs[i]).padStart(10,"0")} 00000 n \n`;tail+=`trailer\n<< /Size ${objs.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;parts.push(Buffer.from(tail,"binary"));return Buffer.concat(parts)}
function splitAt(s="",needle){const i=String(s).indexOf(needle);return i<0?[String(s),""]:[s.slice(0,i),s.slice(i)]}function paras(s=""){return String(s).split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean)}function subheading(text=""){const value=String(text),period=value.match(/^([^.:]{2,80}\.)\s+(.+)$/s),colon=value.match(/^([A-Z][A-Z -]{2,30}:)\s+(.+)$/s),m=period||colon;return m?[m[1],m[2]]:["",value]}function glyphWidth(c){if(c===" ")return.25;if(/[A-Z]/.test(c))return c==="I"?.33:c==="M"||c==="W"?.9:.67;if(/[a-z]/.test(c))return/[il]/.test(c)?.28:/[mw]/.test(c)?.72:/[frt]/.test(c)?.36:.45;if(/[0-9]/.test(c))return.5;return.3}function textWidth(s,size,bold=false){return[...String(s)].reduce((n,c)=>n+glyphWidth(c),0)*size*(bold?1.02:1)}function wordSpace(s,width,size,bold=false){const spaces=(String(s).match(/ /g)||[]).length;return spaces?Math.max(0,(width-textWidth(s,size,bold))/spaces):0}function wrapToWidth(s,width,size,bold=false){const words=String(s||"").replace(/\s+/g," ").trim().split(" "),out=[];let line="";for(const word of words){const next=(line+" "+word).trim();if(line&&textWidth(next,size,bold)>width){out.push(line);line=word}else line=next}if(line)out.push(line);return out}function esc(s){return String(s||"").replace(/\\/g,"\\\\").replace(/\(/g,"\\(").replace(/\)/g,"\\)").replace(/[^\x20-\x7E]/g,"-")}function buyer(b={}){return[b.name,b.company,b.address,b.cityStateZip].filter(Boolean).join("\n")}function seller(s={}){return[s.legalName||s.name,s.address,s.cityStateZip,s.phone,s.email].filter(Boolean).join("\n")}function address(c){return c.deliveryAddress||[c.buyer?.address,c.buyer?.cityStateZip].filter(Boolean).join("\n")}function warrantySelections(w={}){const type=String(w.type||"").toLowerCase(),hasExplicit=[w.manufacturer,w.trial,w.other].some(value=>typeof value==="boolean");return hasExplicit?{manufacturer:w.manufacturer===true,trial:w.trial===true,other:w.other===true}:{manufacturer:type.includes("manufacturer"),trial:type.includes("30")||type.includes("trial"),other:Boolean(w.text)||(!type.includes("manufacturer")&&!type.includes("30")&&!type.includes("trial"))}}function money(v,c="USD"){return new Intl.NumberFormat("en-US",{style:"currency",currency:c||"USD"}).format(Number(v||0))}function shortDate(v){if(!v)return"";const d=new Date(v);return`${d.getUTCMonth()+1}-${d.getUTCDate()}-${d.getUTCFullYear()}`}function sellerDate(v){if(!v)return"";const d=new Date(v);return`${d.getUTCDate()}-${d.getUTCMonth()+1}-${d.getUTCFullYear()}`}function longDate(v){if(!v)return"";return new Intl.DateTimeFormat("en-US",{timeZone:"UTC",month:"long",day:"numeric",year:"numeric"}).format(new Date(v)).replace(",","")}function warrantyDate(v){return v?new Intl.DateTimeFormat("en-US",{timeZone:"UTC",month:"long",day:"numeric",year:"numeric"}).format(new Date(v)):""}
