import mongoose from "mongoose";

const productSchema = new mongoose.Schema({
  // Required fields
  name: { type: String, required: true, trim: true },
  category: { type: String, enum: ["agriculture", "construction", "attachments"], required: true },
  price: { type: Number, required: true },
  year: { type: Number, required: true },
  manufacturer: { type: String, required: true, trim: true },
  model: { type: String, required: true, trim: true },

  // Optional core fields
  fuel: { type: String, trim: true, default: "" },
  condition: { type: String, enum: ["New", "Used"], default: "Used" },
  hours: { type: Number, default: 0 },
  description: { type: String, trim: true },
  engineHorsepower: { type: Number, default: 0 },
  loader: { type: String, default: "" },
  backhoe: { type: String, default: "" },
  cab: { type: String, default: "" },
  drive: { type: String, default: "" },
  transmissionType: { type: String, default: "" },
  axle: { type: String, default: "" },
  hydraulicSpout: { type: String, default: "" },
  monitor: { type: String, default: "" },
  PTOSpeed: { type: String, default: "" },
  scale: { type: String, default: "" },
  serialNumber: { type: String, default: "" },
  size: { type: String, default: "" },
  tarp: { type: String, default: "" },
  tiresOrTracks: { type: String, default: "" },
  trackWidth: { type: String, default: "" },
  unloadingAugerDiameter: { type: String, default: "" },
  unloadingAugerPosition: { type: String, default: "" },
  vin: { type: String, default: "" },

  // New optional fields
  showing: { type: String, default: "" },
  standardFlow: { type: String, default: "" },
  additionalInformation: { type: String, default: "" },
  arm: { type: String, default: "" },
  armLength: { type: String, default: "" },
  athensDlrPdi: { type: String, default: "" },
  auxiliaryHydraulics: { type: String, default: "" },
  auxiliaryLighting: { type: String, default: "" },
  bucketSize: { type: String, default: "" },
  bucket: { type: String, default: "" },
  engineTier: { type: String, default: "" },
  backAuxiliaryHydraulics: { type: String, default: "" },
  backBucketWidth: { type: String, default: "" },
  backfillBlade: { type: String, default: "" },
  batteryType: { type: String, default: "" },
  blockHeater: { type: String, default: "" },
  boomSwing: { type: String, default: "" },
  boomType: { type: String, default: "" },
  bucketWidth: { type: String, default: "" },
  camera: { type: String, default: "" },
  catKey: { type: String, default: "" },
  counterweight: { type: String, default: "" },
  counterweightType: { type: String, default: "" },
  coupler: { type: String, default: "" },
  digDepth: { type: String, default: "" },
  engineMake: { type: String, default: "" },
  engineManufacturer: { type: String, default: "" },
  engineModel: { type: String, default: "" },
  engineOutput: { type: String, default: "" },
  engineTurbo: { type: String, default: "" },
  extendAHoe: { type: String, default: "" },
  exteriorLighting: { type: String, default: "" },
  fisier: { type: String, default: "" },
  forkLength: { type: String, default: "" },
  forkWidth: { type: String, default: "" },
  frontAuxiliaryHydraulics: { type: String, default: "" },
  frontCoupler: { type: String, default: "" },
  frontElectric: { type: String, default: "" },
  frontWheelSize: { type: String, default: "" },
  frontWheelType: { type: String, default: "" },
  fuelCapacity: { type: String, default: "" },
  fuelType: { type: String, default: "" },
  gradeControl: { type: String, default: "" },
  groundPressure: { type: String, default: "" },
  headings: { type: String, default: "" },
  headlightsWork: { type: String, default: "" },
  heater: { type: String, default: "" },
  height: { type: String, default: "" },
  hydraulicHighFlow: { type: String, default: "" },
  keylessStart: { type: String, default: "" },
  length: { type: String, default: "" },
  liftCapacity: { type: String, default: "" },
  liftType: { type: String, default: "" },
  lines: { type: String, default: "" },
  longUndercarriage: { type: String, default: "" },
  maxCapacity: { type: String, default: "" },
  maxDumpHeight: { type: String, default: "" },
  maxForwardReach: { type: String, default: "" },
  maxTravelSpeed: { type: String, default: "" },
  maxTravelSpeedEmpty: { type: String, default: "" },
  maximumLiftHeight: { type: String, default: "" },
  monitorNextGen: { type: String, default: "" },
  numberOfBuckets: { type: String, default: "" },
  numberOfSpeeds: { type: String, default: "" },
  operatingCapacity: { type: String, default: "" },
  operatingWeight: { type: String, default: "" },
  operatorControls: { type: String, default: "" },
  pack: { type: String, default: "" },
  packing: { type: String, default: "" },
  patternChanger: { type: String, default: "" },
  powerType: { type: String, default: "" },
  premiumDisplayPanel: { type: String, default: "" },
  productConfiguration: { type: String, default: "" },
  quickAttach: { type: String, default: "" },
  rops: { type: String, default: "" },
  rearWheelSize: { type: String, default: "" },
  rearWheelType: { type: String, default: "" },
  rearviewCamera: { type: String, default: "" },
  rideControl: { type: String, default: "" },
  seatMaterial: { type: String, default: "" },
  seatType: { type: String, default: "" },
  selfLeveling: { type: String, default: "" },
  shippingHeight: { type: String, default: "" },
  shippingLength: { type: String, default: "" },
  shippingWeight: { type: String, default: "" },
  shippingWidth: { type: String, default: "" },
  tailSwingConfiguration: { type: String, default: "" },
  tailSwingRadius: { type: String, default: "" },
  telematics: { type: String, default: "" },
  thumb: { type: String, default: "" },
  thumbType: { type: String, default: "" },
  tippingLoad: { type: String, default: "" },
  trackShoeWidth: { type: String, default: "" },
  trackSize: { type: String, default: "" },
  trackType: { type: String, default: "" },
  travelSpeed: { type: String, default: "" },
  undercarriageType: { type: String, default: "" },
  wheelSize: { type: String, default: "" },
  wheelType: { type: String, default: "" },
  width: { type: String, default: "" },
  separatorHours: { type: String, default: "" },
  stockNumber: {
    type: Number,
    unique: true,
    default: () => Math.floor(100000 + Math.random() * 900000),
  },
  imgs: { type: [String], default: [] },
  createdAt: { type: Date, default: Date.now },
});

export default mongoose.models.Product || mongoose.model("Product", productSchema); 